<?php

// Invitación de muestra "bautizo-emilia" exportada tal cual desde la base de datos.
// Las fotos y videos ya están en Cloudinary; los invitados se relacionan por su qr_code_token.

return [
    'invitation' => [
        'slug' => 'bautizo-emilia',
        'title' => 'Bautizo de Emilia',
        'template' => 'invitations.templates.bautizo-cielo',
        'event_type' => [
            'slug' => 'bautizos',
            'name' => 'Bautizos',
        ],
        'event_date' => '2026-10-25 11:00:00',
        'status' => 'active',
        'expires_at' => '2027-04-25',
    ],
    'modules' => [
        'config' => [
            'colores' => [
                'primary' => '#C48E9B',
                'secondary' => '#C9A96E',
                'accent' => '#F6E4E8',
                'text' => '#3A2E33',
                'background' => '#FFFBFC',
            ],
            'tipografias' => [
                'titulos' => 'Lora',
                'cuerpo' => 'Nunito Sans',
                'script' => 'Dancing Script',
            ],
            'modulos' => [
                'bienvenida' => true,
                'video' => true,
                'musica' => true,
                'galeria' => true,
                'itinerario' => true,
                'dress_code' => true,
                'destacados' => true,
                'ubicacion' => true,
                'hashtag' => true,
                'encuestas' => true,
                'playlist' => true,
                'regalos' => true,
                'rsvp' => true,
                'fotomural' => true,
                'cuenta_regresiva' => true,
                'agendar' => true,
                'post_evento' => true,
            ],
            'template' => 'invitations.templates.bautizo-cielo',
        ],
        'bienvenida' => [
            'nombre_quinceanera' => 'Emilia Sofía',
            'subtitulo' => 'Mi bautizo',
            'mensaje' => 'Con la alegría de mis papás, Gabriela y Rodrigo, y la bendición de Dios, te invito a acompañarme en el día en que recibiré el sacramento del bautismo.',
            'fecha_texto' => 'Domingo 25 de octubre, 2026',
            'mensaje_post_evento' => 'Gracias por acompañarme en un día tan especial para mi familia.',
            'imagen_hero' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364921/bida-events/bautizo-emilia/hero/383515803_cspv49.jpg',
        ],
        'ubicacion' => [
            'lat' => -17.372,
            'lng' => -66.159,
            'nombre_lugar' => 'Parroquia Nuestra Señora de Fátima',
            'direccion' => 'Av. Santa Cruz esquina calle Beni, Cochabamba',
            'maps_url' => 'https://maps.google.com/?q=-17.3720,-66.1590',
            'nota' => 'Después de la misa te esperamos en el Salón Jardín Las Lilas, a tres cuadras de la parroquia.',
            'imagen_lugar' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_600,h_400,c_fill,q_auto,f_auto/v1789364925/bida-events/bautizo-emilia/ubicacion/281837629_jnl08f.jpg',
        ],
        'itinerario' => [
            'titulo' => 'Mi día',
            'eventos' => [
                [
                    'hora' => '11:00',
                    'titulo' => 'Misa de bautizo',
                    'icono' => 'ceremonia',
                    'descripcion' => 'En la Parroquia Nuestra Señora de Fátima',
                ],
                [
                    'hora' => '12:00',
                    'titulo' => 'Fotos en familia',
                    'icono' => 'fotos',
                    'descripcion' => 'En el atrio de la parroquia',
                ],
                [
                    'hora' => '12:30',
                    'titulo' => 'Recepción',
                    'icono' => 'recepcion',
                    'descripcion' => 'Salón Jardín Las Lilas',
                ],
                [
                    'hora' => '13:30',
                    'titulo' => 'Almuerzo',
                    'icono' => 'cena',
                    'descripcion' => 'Compartimos la mesa en familia',
                ],
                [
                    'hora' => '15:00',
                    'titulo' => 'Pastel',
                    'icono' => 'pastel',
                    'descripcion' => 'Un dulce momento para celebrar',
                ],
                [
                    'hora' => '15:30',
                    'titulo' => 'Juegos y sorpresas',
                    'icono' => 'sorpresa',
                    'descripcion' => 'Para los más pequeños de la familia',
                ],
            ],
        ],
        'dress_code' => [
            'sugerencias' => [
                [
                    'para' => 'Damas',
                    'titulo' => 'Vestido o conjunto claro',
                    'descripcion' => 'Telas livianas en blanco o tonos pastel. Zapatos cómodos para la parroquia y el jardín.',
                    'ejemplos' => ['Vestido midi', 'Blusa y pantalón de lino', 'Sandalias bajas'],
                    'imagen' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364927/bida-events/bautizo-emilia/dress-code/146069285_jz77lx.jpg',
                ],
                [
                    'para' => 'Caballeros',
                    'titulo' => 'Camisa clara y pantalón de vestir',
                    'descripcion' => 'No hace falta traje completo: una camisa clara y un blazer liviano quedan perfectos.',
                    'ejemplos' => ['Camisa blanca', 'Blazer beige', 'Mocasines'],
                    'imagen' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364931/bida-events/bautizo-emilia/dress-code/438775173_sy2jao.jpg',
                ],
                [
                    'para' => 'Niños',
                    'titulo' => 'Cómodos y listos para jugar',
                    'descripcion' => 'Ropa clara que les permita moverse con libertad.',
                    'ejemplos' => ['Vestido de algodón', 'Camisa y bermuda', 'Zapatillas blancas'],
                ],
            ],
            'colores_permitidos' => [
                [
                    'nombre' => 'Rosa empolvado',
                    'hex' => '#E8C4CC',
                ],
                [
                    'nombre' => 'Blanco',
                    'hex' => '#FFFFFF',
                ],
                [
                    'nombre' => 'Beige',
                    'hex' => '#E8DCC8',
                ],
                [
                    'nombre' => 'Celeste',
                    'hex' => '#BFD7EA',
                ],
            ],
            'evitar' => ['Negro total', 'Ropa deportiva'],
            'titulo' => 'Vestimenta',
            'estilo' => 'Casual elegante',
            'descripcion' => 'Colores claros y ropa cómoda para compartir un día en familia.',
        ],
        'destacados' => [
            'chambelanes' => [
                [
                    'nombre' => 'Rodrigo y Martha Vargas',
                    'detalle' => 'Abuelos paternos',
                ],
                [
                    'nombre' => 'Fernando y Rosario Peña',
                    'detalle' => 'Abuelos maternos',
                ],
            ],
            'damitas' => [
                [
                    'nombre' => 'Andrea Peña',
                    'detalle' => 'Hermana de mamá',
                ],
                [
                    'nombre' => 'Mauricio Vargas',
                    'detalle' => 'Hermano de papá',
                ],
            ],
            'padrinos' => [
                [
                    'rol' => 'Padrinos de bautizo',
                    'nombres' => 'Natalia Peña y Javier Soliz',
                    'mensaje' => 'Gracias por aceptar guiarme en la fe y acompañarme toda la vida.',
                ],
                [
                    'rol' => 'Padrinos de vela',
                    'nombres' => 'Sr. Ernesto y Sra. Claudia Rivas',
                    'mensaje' => 'Por encender la luz que me acompañará siempre.',
                ],
                [
                    'rol' => 'Madrina de ropón',
                    'nombres' => 'Sra. Beatriz Soliz',
                ],
            ],
        ],
        'galeria' => [
            'fotos' => [
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364933/bida-events/bautizo-emilia/gallery/537001736_kroyns.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364935/bida-events/bautizo-emilia/gallery/221855171_c1m3ws.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364938/bida-events/bautizo-emilia/gallery/1195042200_mkchov.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364941/bida-events/bautizo-emilia/gallery/214665740_imprpt.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364943/bida-events/bautizo-emilia/gallery/141397802_s1y4xy.jpg',
            ],
            'titulo' => 'Pequeños detalles',
        ],
        'musica' => [
            'titulo' => 'Canción que me encanta',
            'artista' => 'Billie Eilish - Birds of a Feather',
            'audio_url' => 'https://res.cloudinary.com/dwm7mniny/video/upload/v1789366594/bida-events/bautizo-emilia/musica/phpE5A4_j4z8to.mp3',
            'autoplay' => true,
        ],
        'video' => [
            'titulo' => 'Un pequeño gran milagro',
            'video_url' => 'https://res.cloudinary.com/dwm7mniny/video/upload/c_limit,h_1280,q_auto,w_1280/v1789364959/bida-events/bautizo-emilia/video/399031237_uwxncz.mp4',
            'poster' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364968/bida-events/bautizo-emilia/video-poster/399031237-frame_jbl9vx.jpg',
        ],
        'playlist' => [
            'titulo' => 'Música para la tarde',
            'descripcion' => 'Sugiere una canción para el almuerzo en familia.',
            'placeholder' => 'Nombre de la canción o link de YouTube',
        ],
        'hashtag' => [
            'hashtag' => '#BautizoDeEmilia',
            'plataforma' => 'instagram',
            'texto_boton' => 'Comparte tus fotos',
        ],
        'encuestas' => [
            'preguntas' => [
                [
                    'id' => 'parecido',
                    'tipo' => 'single',
                    'pregunta' => '¿A quién se parece más Emilia?',
                    'opciones' => ['A mamá', 'A papá', 'A los dos', 'A la abuela'],
                ],
                [
                    'id' => 'agua-bendita',
                    'tipo' => 'yesno',
                    'pregunta' => '¿Llorará con el agua bendita?',
                    'opciones' => ['Sí, seguro', 'No, es una campeona'],
                ],
                [
                    'id' => 'primera-palabra',
                    'tipo' => 'single',
                    'pregunta' => '¿Cuál será su primera palabra?',
                    'opciones' => ['Mamá', 'Papá', 'Agua', 'Tata'],
                ],
            ],
            'titulo' => 'Adivina adivinador',
        ],
        'regalos' => [
            'sobres' => [
                'titulo' => 'Alcancía',
                'direccion' => 'Habrá una alcancía en la recepción para mis primeros ahorros',
            ],
            'banco' => [
                'banco' => 'Banco Unión',
                'titular' => 'Gabriela Peña Rivas',
                'ci' => '6120984 CB',
                'cuenta' => '1000-4432-7781',
                'qr_url' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364969/bida-events/bautizo-emilia/qr-banco/bautizo-emilia-qr_ijplxg.png',
            ],
            'titulo' => 'Regalos',
            'tienda_url' => '',
            'tienda_texto' => '',
            'opciones' => [],
        ],
        'post_evento' => [
            'titulo' => 'Fotos oficiales',
            'descripcion' => 'Así vivimos el bautizo de Emilia. ¡Gracias por acompañarnos!',
            'fotos' => [
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364972/bida-events/bautizo-emilia/post-evento/466309417_pixqra.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364974/bida-events/bautizo-emilia/post-evento/678111879_wavklh.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364981/bida-events/bautizo-emilia/post-evento/515352927_am6rwk.jpg',
            ],
            'enlace_externo' => '',
        ],
        'rsvp' => [
            'titulo_confirmacion' => '¿Me acompañas?',
            'mensaje_personalizado' => 'Confirma tu asistencia antes del 18 de octubre para que mis papás reserven tu lugar.',
            'texto_confirmado' => '¡Gracias por confirmar! Te espero con mucho cariño.',
            'texto_declinado' => 'Te extrañaré. Gracias por avisar.',
        ],
        'cuenta_regresiva' => [],
        'agendar' => [],
        'fotomural' => [],
    ],
    'guests' => [
        [
            'name' => 'Familia Vargas',
            'phone' => '74340086',
            'passes_allocated' => 4,
            'passes_confirmed' => 4,
            'status' => 'confirmed',
            'table_number' => 'Mesa 1',
            'dietary_restrictions' => null,
            'qr_code_token' => 'H1rEibaOtQHAA5DnYu9JTYxFLoU8M4iZ',
            'confirmed_at' => '2026-09-04 00:10:42',
        ],
        [
            'name' => 'Familia Peña Rivas',
            'phone' => '76274067',
            'passes_allocated' => 5,
            'passes_confirmed' => 5,
            'status' => 'confirmed',
            'table_number' => 'Mesa 1',
            'dietary_restrictions' => null,
            'qr_code_token' => 'cwugMWPtgbm1fpG8Ew07ZX6QuKlyJyd4',
            'confirmed_at' => '2026-08-26 17:52:42',
        ],
        [
            'name' => 'Natalia Peña y Javier Soliz',
            'phone' => '77175735',
            'passes_allocated' => 2,
            'passes_confirmed' => 2,
            'status' => 'confirmed',
            'table_number' => 'Mesa 2',
            'dietary_restrictions' => null,
            'qr_code_token' => 'DEXuUWQSA1xIthyv9mkd2qPuTvQ4ZiAq',
            'confirmed_at' => '2026-09-09 20:55:42',
        ],
        [
            'name' => 'Familia Rivas',
            'phone' => '76250329',
            'passes_allocated' => 4,
            'passes_confirmed' => 3,
            'status' => 'confirmed',
            'table_number' => 'Mesa 3',
            'dietary_restrictions' => 'Un niño con alergia al maní',
            'qr_code_token' => '0V5Nylc0WlBFhbJyHJlzIvbm39PNRkkt',
            'confirmed_at' => '2026-09-07 19:20:42',
        ],
        [
            'name' => 'Andrea Peña',
            'phone' => '76105213',
            'passes_allocated' => 1,
            'passes_confirmed' => 1,
            'status' => 'confirmed',
            'table_number' => 'Mesa 2',
            'dietary_restrictions' => null,
            'qr_code_token' => 'NoKBhDuZOzFAyH9XAaXFeDFMKy1qCfzU',
            'confirmed_at' => '2026-09-04 20:06:42',
        ],
        [
            'name' => 'Familia Soliz',
            'phone' => '71300231',
            'passes_allocated' => 4,
            'passes_confirmed' => 0,
            'status' => 'pending',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => '3WTkholT2SghU6xEYratPDWlwsPercJ7',
            'confirmed_at' => null,
        ],
        [
            'name' => 'Mauricio Vargas y familia',
            'phone' => '71636054',
            'passes_allocated' => 3,
            'passes_confirmed' => 3,
            'status' => 'confirmed',
            'table_number' => 'Mesa 4',
            'dietary_restrictions' => null,
            'qr_code_token' => '75UXPFUbfpD0wW3IM0XPhbl1g3gIZ0OF',
            'confirmed_at' => '2026-08-27 16:12:42',
        ],
        [
            'name' => 'Compañeras de trabajo de Gabriela',
            'phone' => '74353553',
            'passes_allocated' => 3,
            'passes_confirmed' => 0,
            'status' => 'declined',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'HLHlohdXU4bfOvRm1t9IShIsM1sy4LZp',
            'confirmed_at' => '2026-09-11 21:37:42',
        ],
    ],
    'contributions' => [
        [
            'guest' => 'H1rEibaOtQHAA5DnYu9JTYxFLoU8M4iZ',
            'type' => 'song_request',
            'content_text' => 'Color esperanza — Diego Torres',
            'file_path' => null,
            'created_at' => '2026-09-06 21:45:42',
        ],
        [
            'guest' => 'cwugMWPtgbm1fpG8Ew07ZX6QuKlyJyd4',
            'type' => 'song_request',
            'content_text' => 'Somewhere Over the Rainbow — Israel Kamakawiwo\'ole',
            'file_path' => null,
            'created_at' => '2026-09-02 22:21:42',
        ],
        [
            'guest' => null,
            'type' => 'song_request',
            'content_text' => 'Here Comes the Sun — The Beatles',
            'file_path' => null,
            'created_at' => '2026-09-10 23:15:42',
        ],
        [
            'guest' => '0V5Nylc0WlBFhbJyHJlzIvbm39PNRkkt',
            'type' => 'song_request',
            'content_text' => 'Hoy — Gloria Estefan',
            'file_path' => null,
            'created_at' => '2026-09-07 19:51:42',
        ],
        [
            'guest' => 'H1rEibaOtQHAA5DnYu9JTYxFLoU8M4iZ',
            'type' => 'live_photo',
            'content_text' => null,
            'file_path' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_500,h_500,c_fill,q_auto,f_auto/v1789364983/bida-events/bautizo-emilia/fotomural/610166445_pgjdyt.jpg',
            'created_at' => '2026-09-11 07:49:44',
        ],
        [
            'guest' => 'cwugMWPtgbm1fpG8Ew07ZX6QuKlyJyd4',
            'type' => 'live_photo',
            'content_text' => null,
            'file_path' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_500,h_500,c_fill,q_auto,f_auto/v1789364986/bida-events/bautizo-emilia/fotomural/307004116_rvtpqr.jpg',
            'created_at' => '2026-09-12 17:49:47',
        ],
        [
            'guest' => 'DEXuUWQSA1xIthyv9mkd2qPuTvQ4ZiAq',
            'type' => 'live_photo',
            'content_text' => null,
            'file_path' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_500,h_500,c_fill,q_auto,f_auto/v1789364990/bida-events/bautizo-emilia/fotomural/673371022_sovjeg.jpg',
            'created_at' => '2026-09-12 06:49:50',
        ],
    ],
    'poll_votes' => [
        [
            'poll' => 'parecido',
            'option' => 2,
            'guest' => 'H1rEibaOtQHAA5DnYu9JTYxFLoU8M4iZ',
            'voter_key' => 'YhAOe9p0O69I7gMZtRWo0ZOBgHg9oiMmQu7ow2ih',
            'created_at' => '2026-09-09 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 2,
            'guest' => 'cwugMWPtgbm1fpG8Ew07ZX6QuKlyJyd4',
            'voter_key' => 'BxB6qqXDccWcnTZhyoIpmobXUBMhrtMG3P679GrO',
            'created_at' => '2026-09-07 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 2,
            'guest' => 'DEXuUWQSA1xIthyv9mkd2qPuTvQ4ZiAq',
            'voter_key' => 'R0HEoTzOtci3X3PTlMfUKDYAF6GDZkOb9SKjYffw',
            'created_at' => '2026-09-11 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 2,
            'guest' => '0V5Nylc0WlBFhbJyHJlzIvbm39PNRkkt',
            'voter_key' => 'd3tbvinTKbRUe8wyJGuXnHmGE3trrHBObNvrXxWZ',
            'created_at' => '2026-09-07 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 3,
            'guest' => 'NoKBhDuZOzFAyH9XAaXFeDFMKy1qCfzU',
            'voter_key' => 'YuBqghsVRQYsr9SESwgS88AkC5z0INo5fI7BxpIk',
            'created_at' => '2026-09-06 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 3,
            'guest' => '75UXPFUbfpD0wW3IM0XPhbl1g3gIZ0OF',
            'voter_key' => 'irRJ1DkJ6jwbdQTy384kWtR89nsWa6jtmayDyDkr',
            'created_at' => '2026-09-02 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'TiAmTQffVkJnIV6H4DAVM0aBMNRQbjaJnpNd2SWF',
            'created_at' => '2026-09-04 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'Tm8fIcJrxHVTDAVgg8YqebtmOKZ5ypAjATqkldrY',
            'created_at' => '2026-09-03 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'ANUkBV9uaAWnt81Ii0GipimcPiBdLnZyVW83Ojt5',
            'created_at' => '2026-09-14 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 2,
            'guest' => null,
            'voter_key' => '0soshQdnVaAAd823eyAgEycNtHmq7flYDnHAWHgX',
            'created_at' => '2026-09-06 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'nguhCM9Maawx8kAVpSg4wYR3EqFA49asyDOwAwFw',
            'created_at' => '2026-09-10 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'xEf92z3UXSVxz0k6keyZLtFyKk0UtkZODhW3utv8',
            'created_at' => '2026-09-03 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'FoM5VwtgvTaiQX96FaGsfeblK4Cbh9Pilgycqu2m',
            'created_at' => '2026-08-30 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'xl1RDqsT4hieCJVgIiuoVuvyYRQNwowySXe1G8Nq',
            'created_at' => '2026-09-06 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'e1ZcIiVz6muD1bjQ6zQOT7We4PGFfWyrNDao1wkC',
            'created_at' => '2026-09-06 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'xUO1HhCfic87Jq6TtE6cL31fJhVKYGo2bUst4k7r',
            'created_at' => '2026-09-06 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'pfkqd9uHpwrQeDYnNRzG5cfLV2l6xkSLnoLoAkaW',
            'created_at' => '2026-09-01 01:49:50',
        ],
        [
            'poll' => 'parecido',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'X1H5bHqTggnUHkk4mRg8Qc9ohk94vpdB9qnhsJsW',
            'created_at' => '2026-09-09 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 1,
            'guest' => 'H1rEibaOtQHAA5DnYu9JTYxFLoU8M4iZ',
            'voter_key' => '4wYs71jyns3PxINEELU6R56de0CNS7wMwKjkUL24',
            'created_at' => '2026-09-01 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 1,
            'guest' => 'cwugMWPtgbm1fpG8Ew07ZX6QuKlyJyd4',
            'voter_key' => 'A8RWrHneqDQdP5Yhz1kSsgOqjFYiD0Ztw8AfEDWd',
            'created_at' => '2026-09-02 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 1,
            'guest' => 'DEXuUWQSA1xIthyv9mkd2qPuTvQ4ZiAq',
            'voter_key' => 'yzE6yKWgc4ly8476H00DLTwhAXQVMAJQtsRvpJSL',
            'created_at' => '2026-09-08 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 1,
            'guest' => '0V5Nylc0WlBFhbJyHJlzIvbm39PNRkkt',
            'voter_key' => 'dR9lDkN2759OQ2bN26qJWkmMgbWr3ZMuNnP6U3J1',
            'created_at' => '2026-09-06 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 1,
            'guest' => 'NoKBhDuZOzFAyH9XAaXFeDFMKy1qCfzU',
            'voter_key' => 'nDq1rjIwf8RNQJgP5AWcGj2113S7BZ8TuWG8a9Cg',
            'created_at' => '2026-09-09 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 1,
            'guest' => '75UXPFUbfpD0wW3IM0XPhbl1g3gIZ0OF',
            'voter_key' => 'P69DsoeycTDFg7Af5ajK6sMk2eRRr9tRWnfmc4l2',
            'created_at' => '2026-09-13 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'OXsRBqYBbrcGsPnR4BjEyNTQrs31vvrg7vmZbBLO',
            'created_at' => '2026-09-03 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'jrp3JRVMbIetVr7sjCRs1exHlQeNlImbTDm0GNUF',
            'created_at' => '2026-08-30 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 0,
            'guest' => null,
            'voter_key' => '6IjsFzbpPi1lzDZ2DXPGANMkum0zGXf77z1WDwFF',
            'created_at' => '2026-09-07 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'kO0kzaXkzXybR4IfQ55Tv1Ud8xttbLT4LYf26dzb',
            'created_at' => '2026-09-03 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'ip150BDz1rnp5ezv4uTUASUbLTPX8Ebbmn7EtROG',
            'created_at' => '2026-09-09 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 1,
            'guest' => null,
            'voter_key' => '2Bx8ML9l7iow3FXstf4TuyDJ0VYpDV3QGGlCp0kj',
            'created_at' => '2026-09-02 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'ZWtPQtkIeGtDvsb6P7kzFpAxmopjiG3em5RDpzwa',
            'created_at' => '2026-09-08 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'NvUTtPUMDiwJ7Kp9TrMg2lxuVeuBJptrr3kWNfhM',
            'created_at' => '2026-09-07 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'ecywtHIzwSAIQe91RbJOgcipVNSCn0n36yn1jmKe',
            'created_at' => '2026-09-09 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'myaZdPdX63P9nueKAdlP8RLMeQTgvQPJ3FkLqN4C',
            'created_at' => '2026-09-13 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'WO7fzQekkbkTY3IwKNOTGdFVtB6QSI5t2uJHgO2T',
            'created_at' => '2026-09-09 01:49:50',
        ],
        [
            'poll' => 'agua-bendita',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'LiRr3cUUvK6McptdwhOFGxDyCss40WiQFYoQ9uZt',
            'created_at' => '2026-08-31 01:49:50',
        ],
        [
            'poll' => 'primera-palabra',
            'option' => 0,
            'guest' => 'H1rEibaOtQHAA5DnYu9JTYxFLoU8M4iZ',
            'voter_key' => 'OnS8bgSILmdFvocEQu63tOILP5vr38ngbE3IpF22',
            'created_at' => '2026-09-14 01:49:50',
        ],
        [
            'poll' => 'primera-palabra',
            'option' => 0,
            'guest' => 'cwugMWPtgbm1fpG8Ew07ZX6QuKlyJyd4',
            'voter_key' => 'aiwkk2HwtQFonZU7gsksI70ZEp73MLhgT8xBKEco',
            'created_at' => '2026-09-10 01:49:50',
        ],
        [
            'poll' => 'primera-palabra',
            'option' => 2,
            'guest' => 'DEXuUWQSA1xIthyv9mkd2qPuTvQ4ZiAq',
            'voter_key' => '8GiOsPT6WFwTvuv1UUCprAKHZEVjknxiVWThiepC',
            'created_at' => '2026-09-05 01:49:50',
        ],
        [
            'poll' => 'primera-palabra',
            'option' => 3,
            'guest' => '0V5Nylc0WlBFhbJyHJlzIvbm39PNRkkt',
            'voter_key' => 'o4XpkPWtxvqNSgVBZBvtD5pFzkRPWps0U92XkHAQ',
            'created_at' => '2026-09-01 01:49:50',
        ],
        [
            'poll' => 'primera-palabra',
            'option' => 2,
            'guest' => 'NoKBhDuZOzFAyH9XAaXFeDFMKy1qCfzU',
            'voter_key' => 'VwPs6g3f2CSVRyPiMxIGqdsyBYP9pL1KePlg5OUQ',
            'created_at' => '2026-09-01 01:49:50',
        ],
        [
            'poll' => 'primera-palabra',
            'option' => 1,
            'guest' => '75UXPFUbfpD0wW3IM0XPhbl1g3gIZ0OF',
            'voter_key' => 'eNEDhR21ABF3wlJdwhccA8TYPHMKq7lGnp3OLUia',
            'created_at' => '2026-09-11 01:49:50',
        ],
        [
            'poll' => 'primera-palabra',
            'option' => 2,
            'guest' => null,
            'voter_key' => '7r8Hl09mwXJS6TA3DDnZrPtr9QPwORfaXNMaLD7z',
            'created_at' => '2026-09-01 01:49:50',
        ],
        [
            'poll' => 'primera-palabra',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'UHsOw8JgctToJ8h0XOB3unZQ0lvApHHpTC7jZsZG',
            'created_at' => '2026-09-01 01:49:50',
        ],
        [
            'poll' => 'primera-palabra',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'LWmQrmNXJMwpTeoSvyOLbbgxgi2QnVJtR5YW61LO',
            'created_at' => '2026-09-04 01:49:50',
        ],
        [
            'poll' => 'primera-palabra',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'mn93hcArBjKFGQyjBWJc154WySiGkNQTjp4t95kQ',
            'created_at' => '2026-09-13 01:49:50',
        ],
        [
            'poll' => 'primera-palabra',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'KRCrpgoc5gqG4Z631RYJg0e7PMWitYcXYUJFw4hq',
            'created_at' => '2026-09-12 01:49:50',
        ],
        [
            'poll' => 'primera-palabra',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'PJyK6m2oBAUrWPIJpXZqOMxGp1fYsy9tSjsVkh3f',
            'created_at' => '2026-09-01 01:49:50',
        ],
    ],
];
