<?php

// Invitación de muestra "boda-camila-andres" exportada tal cual desde la base de datos.
// Las fotos y videos ya están en Cloudinary; los invitados se relacionan por su qr_code_token.

return [
    'invitation' => [
        'slug' => 'boda-camila-andres',
        'title' => 'Boda de Camila y Andrés',
        'template' => 'invitations.templates.boda-jardin',
        'event_type' => [
            'slug' => 'bodas',
            'name' => 'Bodas',
        ],
        'event_date' => '2026-12-12 16:00:00',
        'status' => 'active',
        'expires_at' => '2027-06-12',
    ],
    'modules' => [
        'config' => [
            'colores' => [
                'primary' => '#A8875A',
                'secondary' => '#5E6B55',
                'accent' => '#EAD9CF',
                'text' => '#3A3530',
                'background' => '#FCF9F4',
            ],
            'tipografias' => [
                'titulos' => 'Cormorant Garamond',
                'cuerpo' => 'Lato',
                'script' => 'Parisienne',
            ],
            'modulos' => [
                'bienvenida' => true,
                'video' => true,
                'musica' => true,
                'galeria' => true,
                'itinerario' => true,
                'dress_code' => true,
                'destacados' => true,
                'ubicacion' => true,
                'hashtag' => true,
                'encuestas' => true,
                'playlist' => true,
                'regalos' => true,
                'rsvp' => true,
                'fotomural' => true,
                'cuenta_regresiva' => true,
                'agendar' => true,
                'post_evento' => true,
            ],
            'template' => 'invitations.templates.boda-jardin',
        ],
        'bienvenida' => [
            'nombre_quinceanera' => 'Camila & Andrés',
            'subtitulo' => 'Nos casamos',
            'mensaje' => 'Después de siete años, un viaje y muchas risas, decidimos decir que sí para siempre. Nos haría muy felices que nos acompañes en el día más importante de nuestras vidas.',
            'fecha_texto' => 'Sábado 12 de diciembre, 2026',
            'mensaje_post_evento' => 'Gracias por ser parte del día más feliz de nuestras vidas.',
            'imagen_hero' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364856/bida-events/boda-camila-andres/hero/238291937_sjvdll.jpg',
        ],
        'ubicacion' => [
            'lat' => -17.3375,
            'lng' => -66.217,
            'nombre_lugar' => 'Hacienda Los Molles',
            'direccion' => 'Camino a Tiquipaya km 6, Cochabamba',
            'maps_url' => 'https://maps.google.com/?q=-17.3375,-66.2170',
            'nota' => 'La ceremonia y la recepción son en el jardín. Habrá transporte desde la Plaza Colón a las 15:00.',
            'imagen_lugar' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_600,h_400,c_fill,q_auto,f_auto/v1789364861/bida-events/boda-camila-andres/ubicacion/219929028_qblimb.jpg',
        ],
        'itinerario' => [
            'titulo' => 'Nuestro día',
            'eventos' => [
                [
                    'hora' => '16:00',
                    'titulo' => 'Ceremonia',
                    'icono' => 'ceremonia',
                    'descripcion' => 'Bajo el arco del jardín',
                ],
                [
                    'hora' => '17:00',
                    'titulo' => 'Cóctel',
                    'icono' => 'recepcion',
                    'descripcion' => 'Música en vivo junto a la fuente',
                ],
                [
                    'hora' => '18:30',
                    'titulo' => 'Entrada de los esposos',
                    'icono' => 'entrada',
                    'descripcion' => 'Te esperamos en el salón principal',
                ],
                [
                    'hora' => '19:00',
                    'titulo' => 'Primer baile',
                    'icono' => 'vals',
                    'descripcion' => 'Nuestro primer baile como esposos',
                ],
                [
                    'hora' => '19:30',
                    'titulo' => 'Brindis y cena',
                    'icono' => 'cena',
                    'descripcion' => 'Menú de tres tiempos',
                ],
                [
                    'hora' => '21:30',
                    'titulo' => 'Pastel',
                    'icono' => 'pastel',
                    'descripcion' => 'Un momento dulce para compartir',
                ],
                [
                    'hora' => '22:00',
                    'titulo' => 'Fiesta',
                    'icono' => 'fiesta',
                    'descripcion' => 'A bailar hasta que el cuerpo aguante',
                ],
                [
                    'hora' => '01:00',
                    'titulo' => 'Hora loca',
                    'icono' => 'hora-loca',
                    'descripcion' => 'Sombreros, luces y batucada',
                ],
            ],
        ],
        'dress_code' => [
            'sugerencias' => [
                [
                    'para' => 'Damas',
                    'titulo' => 'Vestido largo o midi',
                    'descripcion' => 'Telas livianas y tonos tierra o verdes. Tacón ancho para caminar sobre el césped.',
                    'ejemplos' => ['Vestido fluido', 'Satín verde salvia', 'Tacón ancho'],
                    'imagen' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364866/bida-events/boda-camila-andres/dress-code/218746872_zzgdcb.jpg',
                ],
                [
                    'para' => 'Caballeros',
                    'titulo' => 'Traje con moño o corbata',
                    'descripcion' => 'Traje completo en azul, gris o beige. El moño es bienvenido.',
                    'ejemplos' => ['Traje azul', 'Camisa blanca', 'Moño o corbata'],
                    'imagen' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364869/bida-events/boda-camila-andres/dress-code/195197912_amueyg.jpg',
                ],
            ],
            'colores_permitidos' => [
                [
                    'nombre' => 'Salvia',
                    'hex' => '#9CAF88',
                ],
                [
                    'nombre' => 'Terracota',
                    'hex' => '#C4876B',
                ],
                [
                    'nombre' => 'Azul polvo',
                    'hex' => '#9FB4C7',
                ],
                [
                    'nombre' => 'Arena',
                    'hex' => '#D8C3A5',
                ],
            ],
            'evitar' => ['Blanco, marfil o crema', 'Tacones de aguja', 'Jeans o ropa deportiva'],
            'titulo' => 'Dress code',
            'estilo' => 'Formal de jardín',
            'descripcion' => 'Te pedimos reservar el blanco y el marfil para la novia.',
        ],
        'destacados' => [
            'chambelanes' => [
                [
                    'nombre' => 'Rodrigo Salinas',
                    'detalle' => 'Hermano del novio',
                ],
                [
                    'nombre' => 'Diego Ferrufino',
                    'detalle' => 'Amigo de la universidad',
                ],
                [
                    'nombre' => 'Martín Céspedes',
                    'detalle' => 'Compañero de viajes',
                ],
            ],
            'damitas' => [
                [
                    'nombre' => 'Daniela Aguilar',
                    'detalle' => 'Hermana de la novia',
                ],
                [
                    'nombre' => 'Paula Montaño',
                    'detalle' => 'Mejor amiga desde el colegio',
                ],
                [
                    'nombre' => 'Fernanda Rivero',
                    'detalle' => 'Prima y confidente',
                ],
            ],
            'padrinos' => [
                [
                    'rol' => 'Padrinos de velación',
                    'nombres' => 'Sr. Jorge y Sra. Silvia Aguilar',
                    'mensaje' => 'Gracias por enseñarnos con su ejemplo lo que es un matrimonio.',
                ],
                [
                    'rol' => 'Padrinos de anillos',
                    'nombres' => 'Sr. Mauricio y Sra. Ana Salinas',
                    'mensaje' => 'Por acompañarnos desde el primer día de esta historia.',
                ],
                [
                    'rol' => 'Padrinos de lazo',
                    'nombres' => 'Sr. Óscar y Sra. Teresa Ferrufino',
                ],
                [
                    'rol' => 'Padrinos de arras',
                    'nombres' => 'Sr. Luis y Sra. Mónica Céspedes',
                ],
            ],
        ],
        'galeria' => [
            'fotos' => [
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364872/bida-events/boda-camila-andres/gallery/258108791_jqgwpb.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364874/bida-events/boda-camila-andres/gallery/532227184_rrvjtq.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364877/bida-events/boda-camila-andres/gallery/192858832_eqojih.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364879/bida-events/boda-camila-andres/gallery/296715644_n7kcrz.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364882/bida-events/boda-camila-andres/gallery/271978218_tkel3r.jpg',
            ],
            'titulo' => 'Nuestra historia',
        ],
        'musica' => [
            'titulo' => 'Nuestra canción',
            'artista' => 'Lady Gaga, Bruno Mars - Die With A Smile ',
            'audio_url' => 'https://res.cloudinary.com/dwm7mniny/video/upload/v1789366356/bida-events/boda-camila-andres/musica/php4393_c6yqnh.mp3',
            'autoplay' => true,
        ],
        'video' => [
            'titulo' => 'Save the date',
            'video_url' => 'https://res.cloudinary.com/dwm7mniny/video/upload/c_limit,h_1280,q_auto,w_1280/v1789364890/bida-events/boda-camila-andres/video/398765982_d6qtrz.mp4',
            'poster' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364899/bida-events/boda-camila-andres/video-poster/398765982-frame_wwhndk.jpg',
        ],
        'playlist' => [
            'titulo' => 'Canciones para la fiesta',
            'descripcion' => 'Sugiere la canción con la que quieres vernos bailar.',
            'placeholder' => 'Nombre de la canción o link de YouTube',
        ],
        'hashtag' => [
            'hashtag' => '#CamilaYAndres',
            'plataforma' => 'instagram',
            'texto_boton' => 'Comparte tus fotos',
        ],
        'encuestas' => [
            'preguntas' => [
                [
                    'id' => 'primero-en-llorar',
                    'tipo' => 'single',
                    'pregunta' => '¿Quién llorará primero en la ceremonia?',
                    'opciones' => ['El novio', 'La novia', 'Las mamás', 'Todos'],
                ],
                [
                    'id' => 'luna-de-miel',
                    'tipo' => 'single',
                    'pregunta' => '¿A dónde crees que irán de luna de miel?',
                    'opciones' => ['Europa', 'Playa en el Caribe', 'Patagonia', 'Es secreto'],
                ],
                [
                    'id' => 'hora-loca',
                    'tipo' => 'yesno',
                    'pregunta' => '¿Te animas a la hora loca?',
                    'opciones' => ['¡Claro que sí!', 'Mejor miro'],
                ],
            ],
            'titulo' => 'Juguemos un poco',
        ],
        'regalos' => [
            'sobres' => [
                'titulo' => 'Lluvia de sobres',
                'direccion' => 'Habrá un buzón junto a la mesa de los novios',
            ],
            'banco' => [
                'banco' => 'Banco Nacional de Bolivia',
                'titular' => 'Camila Aguilar Rocha',
                'ci' => '7823410 CB',
                'cuenta' => '3000-5561-2290',
                'qr_url' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364900/bida-events/boda-camila-andres/qr-banco/boda-camila-andres-qr_m36sky.png',
            ],
            'titulo' => 'Mesa de regalos',
            'tienda_url' => '',
            'tienda_texto' => '',
            'opciones' => [],
        ],
        'post_evento' => [
            'titulo' => 'Fotos oficiales',
            'descripcion' => 'Revive con nosotros los mejores momentos de la boda.',
            'fotos' => [
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364903/bida-events/boda-camila-andres/post-evento/300029166_hwqnuv.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364906/bida-events/boda-camila-andres/post-evento/488429246_gpwvnc.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364908/bida-events/boda-camila-andres/post-evento/381855881_y7i47o.jpg',
            ],
            'enlace_externo' => '',
        ],
        'rsvp' => [
            'titulo_confirmacion' => '¿Nos acompañas?',
            'mensaje_personalizado' => 'Confirma tu asistencia antes del 20 de noviembre para reservar tu lugar.',
            'texto_confirmado' => '¡Gracias por confirmar! Presenta este pase en la entrada.',
            'texto_declinado' => 'Te extrañaremos. Gracias por avisarnos.',
        ],
        'cuenta_regresiva' => [],
        'agendar' => [],
        'fotomural' => [],
    ],
    'guests' => [
        [
            'name' => 'Familia Aguilar Rocha',
            'phone' => '76161107',
            'passes_allocated' => 4,
            'passes_confirmed' => 4,
            'status' => 'confirmed',
            'table_number' => 'Mesa 1',
            'dietary_restrictions' => null,
            'qr_code_token' => 'aW6qF1WjHGYjwIXMXrNsWFVXbrlmBs4p',
            'confirmed_at' => '2026-08-25 16:38:29',
        ],
        [
            'name' => 'Familia Salinas',
            'phone' => '79185906',
            'passes_allocated' => 4,
            'passes_confirmed' => 4,
            'status' => 'confirmed',
            'table_number' => 'Mesa 1',
            'dietary_restrictions' => null,
            'qr_code_token' => 'sEHIJFyNPWM3eDSpwWjaj7gzJ3K4zAK4',
            'confirmed_at' => '2026-09-11 17:03:29',
        ],
        [
            'name' => 'Paula Montaño y acompañante',
            'phone' => '71388792',
            'passes_allocated' => 2,
            'passes_confirmed' => 2,
            'status' => 'confirmed',
            'table_number' => 'Mesa 6',
            'dietary_restrictions' => 'Vegana',
            'qr_code_token' => 'NjXv9hX87lIp7G59tT9J5mjXMzcFQt9t',
            'confirmed_at' => '2026-08-24 15:48:29',
        ],
        [
            'name' => 'Diego Ferrufino',
            'phone' => '79406789',
            'passes_allocated' => 2,
            'passes_confirmed' => 1,
            'status' => 'confirmed',
            'table_number' => 'Mesa 6',
            'dietary_restrictions' => null,
            'qr_code_token' => 'UxkIABDch6t1PlurGOroDR9Fbb6Xtigk',
            'confirmed_at' => '2026-09-12 21:45:29',
        ],
        [
            'name' => 'Familia Céspedes',
            'phone' => '76295596',
            'passes_allocated' => 3,
            'passes_confirmed' => 3,
            'status' => 'confirmed',
            'table_number' => 'Mesa 3',
            'dietary_restrictions' => null,
            'qr_code_token' => 'vBQ4HcPQSeua3LSC35aCZvawRHCzOgt9',
            'confirmed_at' => '2026-09-04 21:53:29',
        ],
        [
            'name' => 'Familia Rivero',
            'phone' => '72371445',
            'passes_allocated' => 4,
            'passes_confirmed' => 0,
            'status' => 'pending',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'Tj42UNvXleQxnAmDs923hUw4Svg1tq3A',
            'confirmed_at' => null,
        ],
        [
            'name' => 'Ing. Carlos Terrazas',
            'phone' => '71185122',
            'passes_allocated' => 2,
            'passes_confirmed' => 0,
            'status' => 'declined',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'ce0YWxjLO021Ueye9PV7DY0RREjahkDS',
            'confirmed_at' => '2026-09-01 00:30:29',
        ],
        [
            'name' => 'Martín Céspedes y pareja',
            'phone' => '75623326',
            'passes_allocated' => 2,
            'passes_confirmed' => 2,
            'status' => 'confirmed',
            'table_number' => 'Mesa 7',
            'dietary_restrictions' => null,
            'qr_code_token' => 'dotfBjHokBtRwtBRLzmRCQhbg3fCxsH3',
            'confirmed_at' => '2026-08-27 22:20:29',
        ],
        [
            'name' => 'Familia Montaño',
            'phone' => '78345750',
            'passes_allocated' => 5,
            'passes_confirmed' => 4,
            'status' => 'confirmed',
            'table_number' => 'Mesa 4',
            'dietary_restrictions' => 'Una persona sin mariscos',
            'qr_code_token' => 'XmESg17Dj3lAl79VpZc6u4wff8xzdMRB',
            'confirmed_at' => '2026-09-01 23:49:29',
        ],
        [
            'name' => 'Compañeros de oficina de Andrés',
            'phone' => '70598284',
            'passes_allocated' => 6,
            'passes_confirmed' => 0,
            'status' => 'pending',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'vvhqFmA4YzQpBmneQUgFsJzmmN7hrKBt',
            'confirmed_at' => null,
        ],
    ],
    'contributions' => [
        [
            'guest' => 'aW6qF1WjHGYjwIXMXrNsWFVXbrlmBs4p',
            'type' => 'song_request',
            'content_text' => 'Perfect — Ed Sheeran',
            'file_path' => null,
            'created_at' => '2026-09-08 12:42:29',
        ],
        [
            'guest' => 'sEHIJFyNPWM3eDSpwWjaj7gzJ3K4zAK4',
            'type' => 'song_request',
            'content_text' => 'Bésame mucho — Luis Miguel',
            'file_path' => null,
            'created_at' => '2026-09-10 15:56:29',
        ],
        [
            'guest' => null,
            'type' => 'song_request',
            'content_text' => 'La Gozadera — Gente de Zona',
            'file_path' => null,
            'created_at' => '2026-09-11 17:15:29',
        ],
        [
            'guest' => 'UxkIABDch6t1PlurGOroDR9Fbb6Xtigk',
            'type' => 'song_request',
            'content_text' => 'Uptown Funk — Bruno Mars',
            'file_path' => null,
            'created_at' => '2026-09-11 21:29:29',
        ],
        [
            'guest' => 'vBQ4HcPQSeua3LSC35aCZvawRHCzOgt9',
            'type' => 'song_request',
            'content_text' => 'Cómo te atreves — Morat',
            'file_path' => null,
            'created_at' => '2026-09-12 01:14:29',
        ],
        [
            'guest' => 'aW6qF1WjHGYjwIXMXrNsWFVXbrlmBs4p',
            'type' => 'live_photo',
            'content_text' => null,
            'file_path' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_500,h_500,c_fill,q_auto,f_auto/v1789364912/bida-events/boda-camila-andres/fotomural/391848103_qngq0b.jpg',
            'created_at' => '2026-09-12 21:48:33',
        ],
        [
            'guest' => 'sEHIJFyNPWM3eDSpwWjaj7gzJ3K4zAK4',
            'type' => 'live_photo',
            'content_text' => null,
            'file_path' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_500,h_500,c_fill,q_auto,f_auto/v1789364915/bida-events/boda-camila-andres/fotomural/187002737_uihj7o.jpg',
            'created_at' => '2026-09-11 03:48:36',
        ],
        [
            'guest' => 'NjXv9hX87lIp7G59tT9J5mjXMzcFQt9t',
            'type' => 'live_photo',
            'content_text' => null,
            'file_path' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_500,h_500,c_fill,q_auto,f_auto/v1789364918/bida-events/boda-camila-andres/fotomural/631487719_rg1g3q.jpg',
            'created_at' => '2026-09-13 20:48:39',
        ],
    ],
    'poll_votes' => [
        [
            'poll' => 'primero-en-llorar',
            'option' => 2,
            'guest' => 'aW6qF1WjHGYjwIXMXrNsWFVXbrlmBs4p',
            'voter_key' => 'w8xz1TvIuhqYkIoHz6KTZvcl9KUcoiAblb0PrxDx',
            'created_at' => '2026-09-12 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 2,
            'guest' => 'sEHIJFyNPWM3eDSpwWjaj7gzJ3K4zAK4',
            'voter_key' => 'PxysvAfTJsimnQ49yXLDDCdRQYYoDrvlOgrwtqyt',
            'created_at' => '2026-09-10 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 2,
            'guest' => 'NjXv9hX87lIp7G59tT9J5mjXMzcFQt9t',
            'voter_key' => 'MyJBNHTk72PmTVWMt8acceKUUtgPH4khvdRm5T8g',
            'created_at' => '2026-09-13 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 1,
            'guest' => 'UxkIABDch6t1PlurGOroDR9Fbb6Xtigk',
            'voter_key' => '1dgyqFF9i4SifcSGK9UPGnQEOIzJRk8RW55NMztf',
            'created_at' => '2026-09-10 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 0,
            'guest' => 'vBQ4HcPQSeua3LSC35aCZvawRHCzOgt9',
            'voter_key' => 'R269EMar1D5DuS9psEFqJiKQaEioeII7YbH70JeQ',
            'created_at' => '2026-09-02 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 2,
            'guest' => 'dotfBjHokBtRwtBRLzmRCQhbg3fCxsH3',
            'voter_key' => 'Brlqz93WrHV8q4Te4hPH29KtAxX6gwYjIxmhCkMf',
            'created_at' => '2026-09-09 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 1,
            'guest' => 'XmESg17Dj3lAl79VpZc6u4wff8xzdMRB',
            'voter_key' => 'XoTpqd5raASWequwYfEWkvAUHLpUX6cFMD3gAN2N',
            'created_at' => '2026-09-09 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'lC2t4qsHmVYERVOH7elhUCyTMgNg4PL8C1jb6gGK',
            'created_at' => '2026-09-01 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 2,
            'guest' => null,
            'voter_key' => '9fr3yKFS3Lp6GjaWcaDvUznROsb0X7yGLhx37Au8',
            'created_at' => '2026-09-01 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'P7QO1KTAqBqUPEDW0u6vZrfX4RPWFuDctegsG5qT',
            'created_at' => '2026-09-04 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'o8oJadXc7LU1WPsUEpWYgT2zlvEsOb7GCOR0w5vh',
            'created_at' => '2026-08-30 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'qwPAq2nAR3bWXTR5QztX60ebx6yzrCAmcLFAAnE0',
            'created_at' => '2026-08-30 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'nsTAhT49Z2d0wVNxPebVcWP4MeSh49jwEXvvu0zx',
            'created_at' => '2026-09-13 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'iqA9a411KFSyVXMik0RsciciHwtmnSAONSfsCBA1',
            'created_at' => '2026-09-12 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'xot6R3hiAn1hMk1eypvZB8gHqFEIQNyw8b0cStnA',
            'created_at' => '2026-09-03 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'VoyOsNCy3CvmwFUZ4Gx4pWiSCfqZNXXxvo1Stc3l',
            'created_at' => '2026-09-07 01:48:39',
        ],
        [
            'poll' => 'primero-en-llorar',
            'option' => 3,
            'guest' => null,
            'voter_key' => 'wR9OETG00daFIQAcmavEYkwKazLJX417GmcdY9Fj',
            'created_at' => '2026-09-09 01:48:39',
        ],
        [
            'poll' => 'luna-de-miel',
            'option' => 2,
            'guest' => 'aW6qF1WjHGYjwIXMXrNsWFVXbrlmBs4p',
            'voter_key' => 'UOmWenG6WIlkqF6YSyhTha3vFUvs6JamG9jnstzK',
            'created_at' => '2026-08-31 01:48:39',
        ],
        [
            'poll' => 'luna-de-miel',
            'option' => 2,
            'guest' => 'sEHIJFyNPWM3eDSpwWjaj7gzJ3K4zAK4',
            'voter_key' => 'PRygsTRXKchCkGD1RjMfNhSoVnAzLtxAFP1EbFm8',
            'created_at' => '2026-09-12 01:48:39',
        ],
        [
            'poll' => 'luna-de-miel',
            'option' => 2,
            'guest' => 'NjXv9hX87lIp7G59tT9J5mjXMzcFQt9t',
            'voter_key' => 'kdjBJt7SE5YgvRgAoGE92snqMqpxoeBbI58iJbnW',
            'created_at' => '2026-09-10 01:48:39',
        ],
        [
            'poll' => 'luna-de-miel',
            'option' => 0,
            'guest' => 'UxkIABDch6t1PlurGOroDR9Fbb6Xtigk',
            'voter_key' => 'EZbfs8lS807t9YijsBt7eX6UR9Jinej3KMfXDzTK',
            'created_at' => '2026-09-10 01:48:39',
        ],
        [
            'poll' => 'luna-de-miel',
            'option' => 2,
            'guest' => 'vBQ4HcPQSeua3LSC35aCZvawRHCzOgt9',
            'voter_key' => 'AD9v0z5iYigMm11vlwjzdYaCfOf0IOsybFy874We',
            'created_at' => '2026-09-04 01:48:39',
        ],
        [
            'poll' => 'luna-de-miel',
            'option' => 2,
            'guest' => 'dotfBjHokBtRwtBRLzmRCQhbg3fCxsH3',
            'voter_key' => 'S1qRiY0nUhHyV1t6ltZwHBhp5dJWWrN1MMLuHtJk',
            'created_at' => '2026-08-30 01:48:39',
        ],
        [
            'poll' => 'luna-de-miel',
            'option' => 2,
            'guest' => 'XmESg17Dj3lAl79VpZc6u4wff8xzdMRB',
            'voter_key' => 'uwui2xhL91giZtc7Y2ezBqM43RiCByWJQKo6DMuE',
            'created_at' => '2026-09-14 01:48:39',
        ],
        [
            'poll' => 'luna-de-miel',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'P8jkwgAARd1pBYaSUtkYAk8rITv35kWGtZuXrPN9',
            'created_at' => '2026-09-04 01:48:39',
        ],
        [
            'poll' => 'luna-de-miel',
            'option' => 2,
            'guest' => null,
            'voter_key' => '6W1EPmDMsXCnDUP6WO58VCl6Z2SWHbWXaUkeRIWt',
            'created_at' => '2026-09-02 01:48:39',
        ],
        [
            'poll' => 'luna-de-miel',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'f45KctMb5xsOb2MsbJiV08YeAhSxUCeLeyIOVpMy',
            'created_at' => '2026-09-11 01:48:39',
        ],
        [
            'poll' => 'luna-de-miel',
            'option' => 2,
            'guest' => null,
            'voter_key' => '4CMkiJpFTb9t2BK8D29ZfmbpFhJCljhDNC2zmELD',
            'created_at' => '2026-09-02 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => 'aW6qF1WjHGYjwIXMXrNsWFVXbrlmBs4p',
            'voter_key' => 'b5l6PppzvnNTIK0Vac0aufH4ffawzu9TVPZYR0pE',
            'created_at' => '2026-09-12 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => 'sEHIJFyNPWM3eDSpwWjaj7gzJ3K4zAK4',
            'voter_key' => 'MNmxfdBxc9bz8JSigoXosnuiGxXFDSze4fxYOpQ5',
            'created_at' => '2026-09-11 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => 'NjXv9hX87lIp7G59tT9J5mjXMzcFQt9t',
            'voter_key' => '4MZYaeFBN7kZ1UW8lS2nGbU9E6W8KJkzkykGmAJp',
            'created_at' => '2026-09-07 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => 'UxkIABDch6t1PlurGOroDR9Fbb6Xtigk',
            'voter_key' => 'XdXlAR4HVOZI7SWtT1QLQJYznpMIRr2rNxyHUfPr',
            'created_at' => '2026-09-06 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => 'vBQ4HcPQSeua3LSC35aCZvawRHCzOgt9',
            'voter_key' => '9eCGHgIjbjhnYF9aHySVJPlVi82iGSzSAUZZKNmn',
            'created_at' => '2026-09-11 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => 'dotfBjHokBtRwtBRLzmRCQhbg3fCxsH3',
            'voter_key' => 'NnsSz8IVuabqdc9InkoFv9IOyPcKqpWYOROtWDf4',
            'created_at' => '2026-08-30 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => 'XmESg17Dj3lAl79VpZc6u4wff8xzdMRB',
            'voter_key' => '6ZH7PDt96mYzqKptt3M9nljhWHFuTKzHPj5OQOUs',
            'created_at' => '2026-09-02 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'mgG643TJlIKCZkcY1nI7Cq7ALX9nh5ATqI5bIhaT',
            'created_at' => '2026-09-11 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'eylMonIBJZlZWS6WhjLggg9D0jPCk5XMTSdWUJKO',
            'created_at' => '2026-09-14 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'ATXWZfEqJAAko8w37YyLTo9X0woqODy0Bk7gvspF',
            'created_at' => '2026-08-31 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => null,
            'voter_key' => '4cE9s28oxA6ED0C7aFaJfhWsaQRc0XYy7e1zX9j2',
            'created_at' => '2026-09-12 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'WSdtzTjumElaDRDtu24ob6BZftt8EgZMIYU5TODh',
            'created_at' => '2026-09-07 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'OGQMp7HguXsKyD7iTrNBJnaYwXY32I51WoLHRuXe',
            'created_at' => '2026-08-31 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'WzsKWmTp24wySZbCO7bTknCXL0ZPUergKhiMLI3k',
            'created_at' => '2026-09-13 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'D7Xw09PK6EakOtDFzoy44OW9oXl2e1UxaQW1dSi7',
            'created_at' => '2026-09-02 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'FBznEKiKOuwb9g3frrn3XfU4o7at0NfecqzSP5tu',
            'created_at' => '2026-08-30 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'J0cnIOfbUPrHSsi9mY5xiswqzAd9TFCDJpKWW7tT',
            'created_at' => '2026-09-05 01:48:39',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'D5UmXakqOX6bFLFaWug7Xoydafie5FMGn5JIR9Zo',
            'created_at' => '2026-08-31 01:48:39',
        ],
    ],
];
