<?php

// Invitación de muestra "cumple-daniela-30" exportada tal cual desde la base de datos.
// Las fotos y videos ya están en Cloudinary; los invitados se relacionan por su qr_code_token.

return [
    'invitation' => [
        'slug' => 'cumple-daniela-30',
        'title' => 'Cumpleaños 30 de Daniela',
        'template' => 'invitations.templates.cumple-fiesta',
        'event_type' => [
            'slug' => 'cumpleanos',
            'name' => 'Cumpleaños',
        ],
        'event_date' => '2026-10-17 20:30:00',
        'status' => 'active',
        'expires_at' => '2027-04-17',
    ],
    'modules' => [
        'config' => [
            'colores' => [
                'primary' => '#F25C54',
                'secondary' => '#F7B32B',
                'accent' => '#9ADBC5',
                'text' => '#2B2D42',
                'background' => '#FFF8F0',
            ],
            'tipografias' => [
                'titulos' => 'Fredoka',
                'cuerpo' => 'Nunito Sans',
                'script' => 'Dancing Script',
            ],
            'modulos' => [
                'bienvenida' => true,
                'video' => true,
                'musica' => true,
                'galeria' => true,
                'itinerario' => true,
                'dress_code' => true,
                'destacados' => true,
                'ubicacion' => true,
                'hashtag' => true,
                'encuestas' => true,
                'playlist' => true,
                'regalos' => true,
                'rsvp' => true,
                'fotomural' => true,
                'cuenta_regresiva' => true,
                'agendar' => true,
                'post_evento' => true,
            ],
            'template' => 'invitations.templates.cumple-fiesta',
        ],
        'bienvenida' => [
            'nombre_quinceanera' => 'Daniela',
            'subtitulo' => 'Mis 30 años',
            'mensaje' => 'Treinta años, mil historias y las mejores personas a mi lado. Ven a celebrar conmigo una noche de música, brindis y baile en la terraza.',
            'fecha_texto' => 'Sábado 17 de octubre',
            'mensaje_post_evento' => '¡Gracias por venir y hacer de mis 30 una fiesta inolvidable!',
            'imagen_hero' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789365005/bida-events/cumple-daniela-30/hero/343488355-crop_fqc1gz.jpg',
        ],
        'ubicacion' => [
            'lat' => -17.3745,
            'lng' => -66.162,
            'nombre_lugar' => 'Terraza Altavista',
            'direccion' => 'Av. América Oeste 520, piso 12, Cochabamba',
            'maps_url' => 'https://maps.google.com/?q=-17.3745,-66.1620',
            'nota' => 'Sube por el ascensor del edificio hasta el último piso. Hay estacionamiento en la calle lateral.',
            'imagen_lugar' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_600,h_400,c_fill,q_auto,f_auto/v1789365008/bida-events/cumple-daniela-30/ubicacion/442383230_fmhuqb.jpg',
        ],
        'itinerario' => [
            'titulo' => 'Programa de la fiesta',
            'eventos' => [
                [
                    'hora' => '20:30',
                    'titulo' => 'Bienvenida y cócteles',
                    'icono' => 'recepcion',
                    'descripcion' => 'Llega con hambre y ganas de bailar',
                ],
                [
                    'hora' => '21:30',
                    'titulo' => 'Cena',
                    'icono' => 'cena',
                    'descripcion' => 'Mesa de picadas y platos calientes',
                ],
                [
                    'hora' => '22:30',
                    'titulo' => 'Pastel y velas',
                    'icono' => 'pastel',
                    'descripcion' => 'Canta conmigo el cumpleaños feliz',
                ],
                [
                    'hora' => '23:00',
                    'titulo' => 'A bailar',
                    'icono' => 'fiesta',
                    'descripcion' => 'DJ y pista abierta',
                ],
                [
                    'hora' => '00:30',
                    'titulo' => 'Hora loca',
                    'icono' => 'hora-loca',
                    'descripcion' => 'Disfraces, luces y mucha energía',
                ],
                [
                    'hora' => '02:30',
                    'titulo' => 'Despedida',
                    'icono' => 'despedida',
                    'descripcion' => 'Un último abrazo antes de irnos',
                ],
            ],
        ],
        'dress_code' => [
            'sugerencias' => [
                [
                    'para' => 'Todos',
                    'titulo' => 'Un toque de color',
                    'descripcion' => 'Una prenda, un accesorio o un maquillaje con los colores de la fiesta.',
                    'ejemplos' => ['Chaqueta de color', 'Vestido colorido', 'Lentes divertidos'],
                    'imagen' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789365012/bida-events/cumple-daniela-30/dress-code/874367974_phw1ae.jpg',
                ],
                [
                    'para' => 'Para bailar',
                    'titulo' => 'Zapatos cómodos',
                    'descripcion' => 'La pista estará abierta hasta tarde: elige calzado con el que aguantes toda la noche.',
                    'ejemplos' => ['Zapatillas limpias', 'Botines bajos', 'Sandalias cómodas'],
                    'imagen' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789365014/bida-events/cumple-daniela-30/dress-code/533274261_nin7dh.jpg',
                ],
            ],
            'colores_permitidos' => [
                [
                    'nombre' => 'Coral',
                    'hex' => '#F25C54',
                ],
                [
                    'nombre' => 'Amarillo sol',
                    'hex' => '#F7B32B',
                ],
                [
                    'nombre' => 'Menta',
                    'hex' => '#9ADBC5',
                ],
                [
                    'nombre' => 'Fucsia',
                    'hex' => '#E0457B',
                ],
            ],
            'evitar' => ['Todo negro', 'Tacones que no aguanten la pista'],
            'titulo' => 'Dress code',
            'estilo' => 'Casual festivo',
            'descripcion' => 'Ven con algo que tenga color: ¡queremos una foto grupal llena de vida!',
        ],
        'destacados' => [
            'chambelanes' => [
                [
                    'nombre' => 'Mariana Torrico',
                    'detalle' => 'Mejor amiga desde el colegio',
                ],
                [
                    'nombre' => 'Álvaro Pinto',
                    'detalle' => 'Compañero de viajes',
                ],
                [
                    'nombre' => 'Sofía Claure',
                    'detalle' => 'La que organiza todo',
                ],
            ],
            'damitas' => [
                [
                    'nombre' => 'Lucía y Tomás',
                    'detalle' => 'Mis hermanos',
                ],
                [
                    'nombre' => 'Abuela Elena',
                    'detalle' => 'La reina de la pista',
                ],
            ],
            'padrinos' => [
                [
                    'rol' => 'Anfitriones',
                    'nombres' => 'Patricia y Ernesto, mis papás',
                    'mensaje' => 'Gracias por abrirnos la casa y el corazón una vez más.',
                ],
            ],
        ],
        'galeria' => [
            'fotos' => [
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789365018/bida-events/cumple-daniela-30/gallery/471100552_anwwku.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789365022/bida-events/cumple-daniela-30/gallery/380303442_zwbum3.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789365024/bida-events/cumple-daniela-30/gallery/432361417_yjfnwg.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789365027/bida-events/cumple-daniela-30/gallery/303755036_rmdcgz.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789365030/bida-events/cumple-daniela-30/gallery/275565685_ecmuqg.jpg',
            ],
            'titulo' => 'Así se celebra',
        ],
        'musica' => [
            'titulo' => 'Mi canción del año',
            'artista' => 'Sabrina Carpenter - Espresso',
            'audio_url' => 'https://res.cloudinary.com/dwm7mniny/video/upload/v1789366644/bida-events/cumple-daniela-30/musica/phpAB5D_ehfcw2.mp3',
            'autoplay' => true,
        ],
        'video' => [
            'titulo' => 'Pide un deseo',
            'video_url' => 'https://res.cloudinary.com/dwm7mniny/video/upload/c_limit,h_1280,q_auto,w_1280/v1789365036/bida-events/cumple-daniela-30/video/299541776_vhxd7z.mp4',
            'poster' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789365042/bida-events/cumple-daniela-30/video-poster/299541776-frame_rwzkb6.jpg',
        ],
        'playlist' => [
            'titulo' => 'Playlist de la fiesta',
            'descripcion' => 'Sugiere la canción que no puede faltar en la pista.',
            'placeholder' => 'Nombre de la canción o link de YouTube',
        ],
        'hashtag' => [
            'hashtag' => '#Dani30',
            'plataforma' => 'instagram',
            'texto_boton' => 'Comparte tus fotos',
        ],
        'encuestas' => [
            'preguntas' => [
                [
                    'id' => 'genero-pista',
                    'tipo' => 'single',
                    'pregunta' => '¿Qué género abre la pista?',
                    'opciones' => ['Reguetón', 'Cumbia', 'Pop de los 2000', 'Rock'],
                ],
                [
                    'id' => 'edad-aparente',
                    'tipo' => 'single',
                    'pregunta' => '¿Cuántos años aparenta Daniela?',
                    'opciones' => ['25', '28', '30 bien vividos', 'Sin comentarios'],
                ],
                [
                    'id' => 'hora-loca',
                    'tipo' => 'yesno',
                    'pregunta' => '¿Te sumas a la hora loca?',
                    'opciones' => ['¡Obvio!', 'Solo miro'],
                ],
            ],
            'titulo' => 'Juegos de la fiesta',
        ],
        'regalos' => [
            'sobres' => [
                'titulo' => 'Buzón de sobres',
                'direccion' => 'Habrá un buzón junto a la mesa del pastel',
            ],
            'banco' => [
                'banco' => 'Banco BISA',
                'titular' => 'Daniela Claure Vega',
                'ci' => '8123456 CB',
                'cuenta' => '2345-6789-012',
                'qr_url' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789365043/bida-events/cumple-daniela-30/qr-banco/cumple-daniela-30-qr_rmoyba.png',
            ],
            'titulo' => 'Regalos',
            'tienda_url' => '',
            'tienda_texto' => '',
            'opciones' => [],
        ],
        'post_evento' => [
            'titulo' => 'Fotos de la fiesta',
            'descripcion' => 'Las mejores fotos de la noche, ¡gracias por venir!',
            'fotos' => [
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789365046/bida-events/cumple-daniela-30/post-evento/333624016_ewt20b.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789365000/bida-events/cumple-daniela-30/post-evento/31351866-frame_rcjj0n.jpg',
            ],
            'enlace_externo' => '',
        ],
        'rsvp' => [
            'titulo_confirmacion' => '¿Vienes a la fiesta?',
            'mensaje_personalizado' => 'Confirma antes del 10 de octubre para guardarte un lugar en la pista.',
            'texto_confirmado' => '¡Genial! Te espero con el pastel listo.',
            'texto_declinado' => 'Te voy a extrañar. ¡Gracias por avisar!',
        ],
        'cuenta_regresiva' => [],
        'agendar' => [],
        'fotomural' => [],
    ],
    'guests' => [
        [
            'name' => 'Mariana Torrico',
            'phone' => '71449544',
            'passes_allocated' => 2,
            'passes_confirmed' => 2,
            'status' => 'confirmed',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'brpoeahPkyBRhO5NSCLWvxmnZDpbVF8N',
            'confirmed_at' => '2026-09-09 01:17:01',
        ],
        [
            'name' => 'Álvaro Pinto',
            'phone' => '76782508',
            'passes_allocated' => 1,
            'passes_confirmed' => 1,
            'status' => 'confirmed',
            'table_number' => null,
            'dietary_restrictions' => 'Vegetariano',
            'qr_code_token' => 'g46uIKaf7anLWneGqyoYP7kZzqheK8NQ',
            'confirmed_at' => '2026-09-08 17:19:01',
        ],
        [
            'name' => 'Sofía Claure y Diego',
            'phone' => '74993481',
            'passes_allocated' => 2,
            'passes_confirmed' => 2,
            'status' => 'confirmed',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'rOQZ2Kuonp3cUKkdZQrrzHxA8IRDycbS',
            'confirmed_at' => '2026-09-10 00:37:01',
        ],
        [
            'name' => 'Familia Claure Vega',
            'phone' => '76617375',
            'passes_allocated' => 5,
            'passes_confirmed' => 5,
            'status' => 'confirmed',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'vYT8A1Pit54nXfD3zuTUjDkMEiLFF3Fn',
            'confirmed_at' => '2026-09-01 20:36:01',
        ],
        [
            'name' => 'Compañeros de la oficina',
            'phone' => '71241842',
            'passes_allocated' => 6,
            'passes_confirmed' => 4,
            'status' => 'confirmed',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'yfwvm5mztuvVvdx7JA4bRy3Gb1oDRcB2',
            'confirmed_at' => '2026-09-02 21:15:01',
        ],
        [
            'name' => 'Valeria Montes',
            'phone' => '76899823',
            'passes_allocated' => 2,
            'passes_confirmed' => 0,
            'status' => 'pending',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'IBE0YmMWc814TymksDl30Li6mnWWPpyt',
            'confirmed_at' => null,
        ],
        [
            'name' => 'Gonzalo Rivera',
            'phone' => '78350956',
            'passes_allocated' => 1,
            'passes_confirmed' => 0,
            'status' => 'declined',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => '5nJGsbNpwtHKxOUavRbrA00SXDi82Mh1',
            'confirmed_at' => '2026-08-31 17:17:01',
        ],
        [
            'name' => 'Amigas del gimnasio',
            'phone' => '75732141',
            'passes_allocated' => 4,
            'passes_confirmed' => 3,
            'status' => 'confirmed',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'FiEi5sKIROzQEP2Ke5sD0x2Xpzteao6F',
            'confirmed_at' => '2026-08-26 21:10:01',
        ],
        [
            'name' => 'Lucía y Tomás',
            'phone' => '75309456',
            'passes_allocated' => 2,
            'passes_confirmed' => 2,
            'status' => 'confirmed',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'ZNlFRDZe8CEkIVT9jI2IJSqeqEVGqFbM',
            'confirmed_at' => '2026-08-27 01:17:01',
        ],
    ],
    'contributions' => [
        [
            'guest' => 'brpoeahPkyBRhO5NSCLWvxmnZDpbVF8N',
            'type' => 'song_request',
            'content_text' => 'Provenza — Karol G',
            'file_path' => null,
            'created_at' => '2026-09-06 17:48:01',
        ],
        [
            'guest' => 'g46uIKaf7anLWneGqyoYP7kZzqheK8NQ',
            'type' => 'song_request',
            'content_text' => 'Mayores — Becky G',
            'file_path' => null,
            'created_at' => '2026-09-06 13:41:01',
        ],
        [
            'guest' => null,
            'type' => 'song_request',
            'content_text' => 'Levitating — Dua Lipa',
            'file_path' => null,
            'created_at' => '2026-09-04 11:35:01',
        ],
        [
            'guest' => 'vYT8A1Pit54nXfD3zuTUjDkMEiLFF3Fn',
            'type' => 'song_request',
            'content_text' => 'Mi gente — J Balvin',
            'file_path' => null,
            'created_at' => '2026-09-05 21:09:01',
        ],
        [
            'guest' => 'yfwvm5mztuvVvdx7JA4bRy3Gb1oDRcB2',
            'type' => 'song_request',
            'content_text' => 'Dancing Queen — ABBA',
            'file_path' => null,
            'created_at' => '2026-09-11 16:07:01',
        ],
        [
            'guest' => null,
            'type' => 'song_request',
            'content_text' => 'Hips Don\'t Lie — Shakira',
            'file_path' => null,
            'created_at' => '2026-09-02 16:47:01',
        ],
        [
            'guest' => 'brpoeahPkyBRhO5NSCLWvxmnZDpbVF8N',
            'type' => 'live_photo',
            'content_text' => null,
            'file_path' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_500,h_500,c_fill,q_auto,f_auto/v1789365050/bida-events/cumple-daniela-30/fotomural/615038558_chomu3.jpg',
            'created_at' => '2026-09-11 05:09:01',
        ],
        [
            'guest' => 'g46uIKaf7anLWneGqyoYP7kZzqheK8NQ',
            'type' => 'live_photo',
            'content_text' => null,
            'file_path' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_500,h_500,c_fill,q_auto,f_auto/v1789365054/bida-events/cumple-daniela-30/fotomural/380990976_zyehxu.jpg',
            'created_at' => '2026-09-11 06:09:01',
        ],
        [
            'guest' => 'rOQZ2Kuonp3cUKkdZQrrzHxA8IRDycbS',
            'type' => 'live_photo',
            'content_text' => null,
            'file_path' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_500,h_500,c_fill,q_auto,f_auto/v1789365058/bida-events/cumple-daniela-30/fotomural/408044666_m5qvld.jpg',
            'created_at' => '2026-09-12 03:09:01',
        ],
    ],
    'poll_votes' => [
        [
            'poll' => 'genero-pista',
            'option' => 0,
            'guest' => 'brpoeahPkyBRhO5NSCLWvxmnZDpbVF8N',
            'voter_key' => 'OSvz3UntyBnod0ucFT3bB3iFbGbLaeg0xroJbiEu',
            'created_at' => '2026-09-03 02:09:01',
        ],
        [
            'poll' => 'genero-pista',
            'option' => 1,
            'guest' => 'g46uIKaf7anLWneGqyoYP7kZzqheK8NQ',
            'voter_key' => 'gt8cKmH5Fva822PgwNy1PcMkTt5ZYoJ5MDrFv5ws',
            'created_at' => '2026-09-05 02:09:01',
        ],
        [
            'poll' => 'genero-pista',
            'option' => 0,
            'guest' => 'rOQZ2Kuonp3cUKkdZQrrzHxA8IRDycbS',
            'voter_key' => 'bQxL58VpewlE6rovdBKKFxrPniYdunvSHW6QqZ4e',
            'created_at' => '2026-09-05 02:09:01',
        ],
        [
            'poll' => 'genero-pista',
            'option' => 0,
            'guest' => 'vYT8A1Pit54nXfD3zuTUjDkMEiLFF3Fn',
            'voter_key' => 'Ti3leoaGwxbFyQixWJ3vPSvum1lXRF3D95OpVptX',
            'created_at' => '2026-09-12 02:09:01',
        ],
        [
            'poll' => 'genero-pista',
            'option' => 3,
            'guest' => 'yfwvm5mztuvVvdx7JA4bRy3Gb1oDRcB2',
            'voter_key' => 'EjT0v6jH6al0LoJWfd6htMvtt5zZeaCErcQlhFsy',
            'created_at' => '2026-09-01 02:09:01',
        ],
        [
            'poll' => 'genero-pista',
            'option' => 0,
            'guest' => 'FiEi5sKIROzQEP2Ke5sD0x2Xpzteao6F',
            'voter_key' => 'pp5LjU3vdGWqaDArwBUNzsfDDn3E4858zkj0ZusO',
            'created_at' => '2026-09-10 02:09:01',
        ],
        [
            'poll' => 'genero-pista',
            'option' => 3,
            'guest' => 'ZNlFRDZe8CEkIVT9jI2IJSqeqEVGqFbM',
            'voter_key' => 'JXk7Ec1TLSV3dsnNNPOb8s069RSOELcQy0ka6thL',
            'created_at' => '2026-09-13 02:09:01',
        ],
        [
            'poll' => 'genero-pista',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'cRaTYv58flkKdnCDRRwIw1YtWe1ahv13KdWSDe4X',
            'created_at' => '2026-09-04 02:09:01',
        ],
        [
            'poll' => 'genero-pista',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'mUDsSACSQEJ4sZNHWt24cnlakk5jzSYS3D6gFu4b',
            'created_at' => '2026-08-31 02:09:01',
        ],
        [
            'poll' => 'genero-pista',
            'option' => 2,
            'guest' => null,
            'voter_key' => '0IT7JSgK8l9pUdzbVXCgHKNeUvVJvR0n4uyYbunt',
            'created_at' => '2026-08-31 02:09:01',
        ],
        [
            'poll' => 'genero-pista',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'I8WRvPgOY46HRPvL55zT3QynIkl8QVmaQxPTrVtj',
            'created_at' => '2026-09-03 02:09:01',
        ],
        [
            'poll' => 'genero-pista',
            'option' => 3,
            'guest' => null,
            'voter_key' => 'bX3sgjPJlSxaCQPO4YYCzsrVvPn2W83jpjv2Hthc',
            'created_at' => '2026-09-09 02:09:01',
        ],
        [
            'poll' => 'edad-aparente',
            'option' => 1,
            'guest' => 'brpoeahPkyBRhO5NSCLWvxmnZDpbVF8N',
            'voter_key' => 'vsT8eXKkPjxqLULx00KcGsSIAFNQSXggN1mc7KMC',
            'created_at' => '2026-09-12 02:09:01',
        ],
        [
            'poll' => 'edad-aparente',
            'option' => 0,
            'guest' => 'g46uIKaf7anLWneGqyoYP7kZzqheK8NQ',
            'voter_key' => 'tKBmTkJS9G2XBTo5jL91uekqUI21VbKWOzeExDaa',
            'created_at' => '2026-09-11 02:09:01',
        ],
        [
            'poll' => 'edad-aparente',
            'option' => 0,
            'guest' => 'rOQZ2Kuonp3cUKkdZQrrzHxA8IRDycbS',
            'voter_key' => 'EEV3QA2O20VAuAVrc0UQQUEPdMGUBbFJ1U6cLMYE',
            'created_at' => '2026-09-05 02:09:01',
        ],
        [
            'poll' => 'edad-aparente',
            'option' => 0,
            'guest' => 'vYT8A1Pit54nXfD3zuTUjDkMEiLFF3Fn',
            'voter_key' => '4ggZhKAWEYFprGOZngMsvqbtsH3FIZ6WUu9uk24r',
            'created_at' => '2026-09-07 02:09:01',
        ],
        [
            'poll' => 'edad-aparente',
            'option' => 1,
            'guest' => 'yfwvm5mztuvVvdx7JA4bRy3Gb1oDRcB2',
            'voter_key' => 'qYk155REIJHhlDEwNW0JZMSl8TdeBtg9U4OPXMwv',
            'created_at' => '2026-09-08 02:09:01',
        ],
        [
            'poll' => 'edad-aparente',
            'option' => 0,
            'guest' => 'FiEi5sKIROzQEP2Ke5sD0x2Xpzteao6F',
            'voter_key' => '7uA2A0nta3fCdVoqea4ckfEajc6dSFC4cfBADdRD',
            'created_at' => '2026-09-11 02:09:01',
        ],
        [
            'poll' => 'edad-aparente',
            'option' => 2,
            'guest' => 'ZNlFRDZe8CEkIVT9jI2IJSqeqEVGqFbM',
            'voter_key' => 'sodGjpprDEzBccWr63AScY11mSVO1Y93cuKdd0Xh',
            'created_at' => '2026-09-13 02:09:01',
        ],
        [
            'poll' => 'edad-aparente',
            'option' => 0,
            'guest' => null,
            'voter_key' => '3cjLMrLzWxGS3WBU6K3ahtiDR7rLXQUA8Einbuko',
            'created_at' => '2026-09-01 02:09:01',
        ],
        [
            'poll' => 'edad-aparente',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'JkFHT9jiCJMOoZsxWqoxPUhFOdwsADnP3rUYb3Zn',
            'created_at' => '2026-09-04 02:09:01',
        ],
        [
            'poll' => 'edad-aparente',
            'option' => 1,
            'guest' => null,
            'voter_key' => '7Edj1VtaxWSk2oYMWkLUccagXJQueI2FyWDJSGEu',
            'created_at' => '2026-09-04 02:09:01',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => 'brpoeahPkyBRhO5NSCLWvxmnZDpbVF8N',
            'voter_key' => 'bqrHAKKOmvd7jrYFMgEtvAXoweoYbaOkrORWIP5d',
            'created_at' => '2026-09-14 02:09:01',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => 'g46uIKaf7anLWneGqyoYP7kZzqheK8NQ',
            'voter_key' => 'JbdxGdE1HOKUlRY3awxDMck3jGs8ffw3Nsa4ivCD',
            'created_at' => '2026-09-11 02:09:01',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => 'rOQZ2Kuonp3cUKkdZQrrzHxA8IRDycbS',
            'voter_key' => 'Q4AAFmhZnUlzvmRw8sVtXd4KAyBfIKTHEfSTYpai',
            'created_at' => '2026-09-01 02:09:01',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => 'vYT8A1Pit54nXfD3zuTUjDkMEiLFF3Fn',
            'voter_key' => 'qCBPlGlzcHNlfolVzLAVwitc7iOKkCcG2jWpdvD2',
            'created_at' => '2026-09-02 02:09:01',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => 'yfwvm5mztuvVvdx7JA4bRy3Gb1oDRcB2',
            'voter_key' => 'bNYkgM5Rsb8NMc6VKELxPX0S5sxONVX9SHYWIJBR',
            'created_at' => '2026-09-03 02:09:01',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => 'FiEi5sKIROzQEP2Ke5sD0x2Xpzteao6F',
            'voter_key' => 'aBT1LhvB6ZEc5tKCe9oVx6YtrQNXYl0Q6Irp9jsZ',
            'created_at' => '2026-09-13 02:09:01',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => 'ZNlFRDZe8CEkIVT9jI2IJSqeqEVGqFbM',
            'voter_key' => '5f9nTHNtOp2wn6kYLv7cEsLjfBEeib0YHxQxnVKC',
            'created_at' => '2026-09-02 02:09:01',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => null,
            'voter_key' => '8hgoqPXivFMxOFwehOFhx3bxU5c0cwQOUeO0MySz',
            'created_at' => '2026-09-04 02:09:01',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'GeeQfKQ5ekYN3v4X6m9vyQVASkNqOBmEQhGwUDao',
            'created_at' => '2026-09-04 02:09:01',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'IWKFJlzbaJF67g5bVyNIukFPafq7mLcmnLir1T1t',
            'created_at' => '2026-09-11 02:09:01',
        ],
    ],
];
