<?php

// Invitación de muestra "lienzo-casa-molina": la plantilla en blanco («Lienzo») tal como nace,
// con textos de un aniversario de empresa para enseñar que sirve para cualquier evento.

return [
    'invitation' => [
        'slug' => 'lienzo-casa-molina',
        'title' => 'Aniversario 25 de Casa Molina',
        'template' => 'invitations.templates.lienzo',
        'event_type' => [
            'slug' => 'evento-libre',
            'name' => 'Evento libre',
            'code' => 'lienzo',
            'kind' => 'invitation',
        ],
        'event_date' => '2026-11-20 19:30:00',
        'status' => 'active',
        'expires_at' => '2027-05-20',
    ],
    'modules' => [
        'config' => [
            'colores' => [
                'primary' => '#111111',
                'secondary' => '#333333',
                'accent' => '#F1F1F1',
                'text' => '#111111',
                'background' => '#FFFFFF',
            ],
            'tipografias' => [
                'titulos' => 'Inter',
                'cuerpo' => 'Inter',
                'script' => 'Inter',
            ],
            'modulos' => [
                'bienvenida' => true,
                'video' => false,
                'musica' => false,
                'galeria' => false,
                'itinerario' => true,
                'dress_code' => true,
                'destacados' => false,
                'ubicacion' => true,
                'hashtag' => false,
                'encuestas' => false,
                'playlist' => false,
                'regalos' => false,
                'rsvp' => true,
                'fotomural' => false,
                'cuenta_regresiva' => true,
                'agendar' => true,
                'post_evento' => false,
            ],
            'template' => 'invitations.templates.lienzo',
        ],
        'bienvenida' => [
            'nombre_quinceanera' => 'Casa Molina',
            'subtitulo' => 'Celebramos 25 años',
            'mensaje' => 'Un cuarto de siglo haciendo pan en el mismo horno. Queremos celebrarlo con quienes nos acompañaron desde el primer día.',
            'fecha_texto' => 'Viernes 20 de noviembre',
            'mensaje_post_evento' => 'Gracias por acompañarnos en estos 25 años.',
            'imagen_hero' => null,
        ],
        'ubicacion' => [
            'lat' => -17.3935,
            'lng' => -66.1570,
            'nombre_lugar' => 'Casa Molina, sucursal centro',
            'direccion' => 'Calle España 245, Cochabamba',
            'maps_url' => 'https://maps.google.com/?q=-17.3935,-66.1570',
            'nota' => 'La entrada es por el patio.',
            'imagen_lugar' => null,
        ],
        'itinerario' => [
            'titulo' => 'Programa',
            'eventos' => [
                ['hora' => '19:30', 'titulo' => 'Recepción', 'icono' => 'recepcion', 'descripcion' => 'Bienvenida en el patio'],
                ['hora' => '20:00', 'titulo' => 'Unas palabras', 'icono' => 'especial', 'descripcion' => 'La historia de la casa'],
                ['hora' => '20:30', 'titulo' => 'Brindis', 'icono' => 'brindis', 'descripcion' => 'Y degustación de la receta original'],
            ],
        ],
        'dress_code' => [
            'sugerencias' => [
                [
                    'para' => 'Todos',
                    'titulo' => 'Casual elegante',
                    'descripcion' => 'Cómodo y arreglado: la reunión es en el patio.',
                    'ejemplos' => ['Camisa', 'Vestido', 'Chaqueta ligera'],
                    'imagen' => null,
                ],
            ],
            'colores_permitidos' => [],
            'evitar' => [],
            'titulo' => 'Vestimenta',
            'estilo' => 'Casual elegante',
            'descripcion' => '',
        ],
        'destacados' => ['chambelanes' => [], 'damitas' => [], 'padrinos' => []],
        'galeria' => ['fotos' => [], 'titulo' => ''],
        'musica' => ['titulo' => '', 'artista' => '', 'audio_url' => '', 'autoplay' => false],
        'video' => ['titulo' => '', 'video_url' => '', 'poster' => ''],
        'playlist' => ['titulo' => '', 'descripcion' => '', 'placeholder' => ''],
        'hashtag' => ['hashtag' => '', 'plataforma' => 'instagram', 'texto_boton' => ''],
        'encuestas' => ['preguntas' => [], 'titulo' => ''],
        'regalos' => ['sobres' => [], 'banco' => [], 'titulo' => '', 'tienda_url' => '', 'tienda_texto' => '', 'opciones' => []],
        'post_evento' => ['titulo' => '', 'descripcion' => '', 'fotos' => [], 'enlace_externo' => ''],
        'rsvp' => [
            'titulo_confirmacion' => '¿Nos acompañas?',
            'mensaje_personalizado' => 'Confirma antes del 15 de noviembre.',
            'texto_confirmado' => 'Gracias. Te esperamos.',
            'texto_declinado' => 'Gracias por avisarnos.',
        ],
        'cuenta_regresiva' => [],
        'agendar' => [],
        'fotomural' => [],
    ],
    'guests' => [
        [
            'name' => 'Familia Terrazas',
            'phone' => '71230987',
            'passes_allocated' => 3,
            'passes_confirmed' => 3,
            'status' => 'confirmed',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'L1enzoCasaMol1naTerrazas00000001',
            'confirmed_at' => '2026-09-22 09:30:00',
        ],
    ],
    'contributions' => [],
    'poll_votes' => [],
];
