<?php

// Invitación de muestra "xv-isabella" exportada tal cual desde la base de datos.
// Las fotos y videos ya están en Cloudinary; los invitados se relacionan por su qr_code_token.

return [
    'invitation' => [
        'slug' => 'xv-isabella',
        'title' => 'XV Años de Isabella',
        'template' => 'invitations.templates.xv-premium',
        'event_type' => [
            'slug' => 'xv-anos',
            'name' => 'XV Años',
        ],
        'event_date' => '2026-11-21 20:00:00',
        'status' => 'active',
        'expires_at' => '2027-05-21',
    ],
    'modules' => [
        'config' => [
            'colores' => [
                'primary' => '#C97B84',
                'secondary' => '#5C3D42',
                'accent' => '#F8E4E6',
                'text' => '#3A2828',
                'background' => '#FFF8F8',
            ],
            'tipografias' => [
                'titulos' => 'Playfair Display',
                'cuerpo' => 'Montserrat',
                'script' => 'Great Vibes',
            ],
            'modulos' => [
                'bienvenida' => true,
                'video' => true,
                'musica' => true,
                'galeria' => true,
                'itinerario' => true,
                'dress_code' => true,
                'destacados' => true,
                'ubicacion' => true,
                'hashtag' => true,
                'encuestas' => true,
                'playlist' => true,
                'regalos' => true,
                'rsvp' => true,
                'fotomural' => true,
                'cuenta_regresiva' => true,
                'agendar' => true,
                'post_evento' => true,
            ],
            'template' => 'invitations.templates.xv-premium',
        ],
        'bienvenida' => [
            'nombre_quinceanera' => 'Isabella Monserrat',
            'subtitulo' => 'Mis XV Años',
            'mensaje' => 'Hay momentos que se esperan toda la vida. Con la bendición de Dios y el amor de mis papás, Marcelo y Carolina, te invito a celebrar conmigo la noche en que cumplo quince años.',
            'fecha_texto' => 'Sábado 21 de noviembre, 2026',
            'mensaje_post_evento' => 'Gracias por hacer de mis XV una noche de cuento. Nunca olvidaré que estuviste ahí.',
            'imagen_hero' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364754/bida-events/xv-isabella/hero/469198040_apa7ei.jpg',
        ],
        'ubicacion' => [
            'lat' => -16.539,
            'lng' => -68.078,
            'nombre_lugar' => 'Salón Gran Cristal',
            'direccion' => 'Av. Ballivián 1480, Calacoto, La Paz',
            'maps_url' => 'https://maps.google.com/?q=-16.5390,-68.0780',
            'nota' => 'Ingreso por la puerta principal. El salón cuenta con valet parking.',
            'imagen_lugar' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_600,h_400,c_fill,q_auto,f_auto/v1789364759/bida-events/xv-isabella/ubicacion/1476715427_y9c0za.jpg',
        ],
        'itinerario' => [
            'titulo' => 'Mi gran noche',
            'eventos' => [
                [
                    'hora' => '20:00',
                    'titulo' => 'Recepción',
                    'icono' => 'recepcion',
                    'descripcion' => 'Cóctel de bienvenida y fotos en el photobooth',
                ],
                [
                    'hora' => '20:45',
                    'titulo' => 'Entrada de la quinceañera',
                    'icono' => 'entrada',
                    'descripcion' => 'Junto a mis chambelanes',
                ],
                [
                    'hora' => '21:00',
                    'titulo' => 'Cambio de zapatos',
                    'icono' => 'ceremonia',
                    'descripcion' => 'Papá me pone mis primeros tacones',
                ],
                [
                    'hora' => '21:15',
                    'titulo' => 'Vals',
                    'icono' => 'vals',
                    'descripcion' => 'Primero con papá y luego con mis chambelanes',
                ],
                [
                    'hora' => '21:45',
                    'titulo' => 'Brindis y cena',
                    'icono' => 'cena',
                    'descripcion' => 'Menú de tres tiempos',
                ],
                [
                    'hora' => '23:00',
                    'titulo' => 'Pastel',
                    'icono' => 'pastel',
                    'descripcion' => 'Partimos el pastel en familia',
                ],
                [
                    'hora' => '23:30',
                    'titulo' => 'Fiesta',
                    'icono' => 'fiesta',
                    'descripcion' => 'DJ y pista abierta',
                ],
                [
                    'hora' => '01:00',
                    'titulo' => 'Hora loca',
                    'icono' => 'hora-loca',
                    'descripcion' => 'Batucada, antifaces y luces',
                ],
            ],
        ],
        'dress_code' => [
            'sugerencias' => [
                [
                    'para' => 'Damas',
                    'titulo' => 'Vestido largo de gala',
                    'descripcion' => 'Vestidos largos en tonos joya o neutros. Elige un tacón cómodo: habrá vals y mucha pista.',
                    'ejemplos' => ['Vestido satinado', 'Brillos sutiles', 'Tacón medio'],
                    'imagen' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364765/bida-events/xv-isabella/dress-code/414455217_ydvboj.jpg',
                ],
                [
                    'para' => 'Caballeros',
                    'titulo' => 'Traje oscuro o smoking',
                    'descripcion' => 'Traje completo en negro, azul noche o gris oscuro, con corbata o moño.',
                    'ejemplos' => ['Smoking', 'Traje azul noche', 'Moño negro'],
                    'imagen' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364769/bida-events/xv-isabella/dress-code/320836594_ih6ejt.jpg',
                ],
            ],
            'colores_permitidos' => [
                [
                    'nombre' => 'Esmeralda',
                    'hex' => '#2E6B5A',
                ],
                [
                    'nombre' => 'Azul noche',
                    'hex' => '#1F2A44',
                ],
                [
                    'nombre' => 'Vino',
                    'hex' => '#6E2436',
                ],
                [
                    'nombre' => 'Champagne',
                    'hex' => '#E9D8BE',
                ],
            ],
            'evitar' => ['Rosa palo y dorado', 'Blanco total', 'Jeans o zapatillas'],
            'titulo' => 'Código de vestimenta',
            'estilo' => 'Gala',
            'descripcion' => 'Te pedimos reservar el rosa palo y el dorado para la quinceañera.',
        ],
        'destacados' => [
            'chambelanes' => [
                [
                    'nombre' => 'Sebastián Rojas',
                    'iniciales' => 'SR',
                    'detalle' => 'Mi mejor amigo desde primaria',
                ],
                [
                    'nombre' => 'Nicolás Gutiérrez',
                    'iniciales' => 'NG',
                    'detalle' => 'Compañero de curso',
                ],
                [
                    'nombre' => 'Joaquín Vargas',
                    'iniciales' => 'JV',
                    'detalle' => 'Primo y cómplice de travesuras',
                ],
                [
                    'nombre' => 'Matías Arce',
                    'iniciales' => 'MA',
                    'detalle' => 'Del grupo de danza',
                ],
                [
                    'nombre' => 'Adrián Quiroga',
                    'iniciales' => 'AQ',
                    'detalle' => 'Amigo de la familia',
                ],
            ],
            'damitas' => [
                [
                    'nombre' => 'Valentina Rojas',
                    'iniciales' => 'VR',
                    'detalle' => 'Mi hermana y confidente',
                ],
                [
                    'nombre' => 'Luciana Paz',
                    'iniciales' => 'LP',
                    'detalle' => 'Mi mejor amiga',
                ],
                [
                    'nombre' => 'Antonella Suárez',
                    'iniciales' => 'AS',
                    'detalle' => 'Prima favorita',
                ],
                [
                    'nombre' => 'Camila Salinas',
                    'iniciales' => 'CS',
                    'detalle' => 'Compañera de aventuras',
                ],
            ],
            'padrinos' => [
                [
                    'rol' => 'Padrinos de honor',
                    'nombres' => 'Sr. Gonzalo y Sra. Patricia Mendoza',
                    'mensaje' => 'Gracias por acompañarme en cada paso y ser un ejemplo para mí.',
                ],
                [
                    'rol' => 'Padrinos de vals',
                    'nombres' => 'Sr. Ramiro y Sra. Lucía Arteaga',
                    'mensaje' => 'Por enseñarme que la vida también se baila.',
                ],
                [
                    'rol' => 'Madrina de anillo',
                    'nombres' => 'Sra. Verónica Salazar',
                ],
                [
                    'rol' => 'Padrinos de pastel',
                    'nombres' => 'Sr. Hugo y Sra. Carmen Villarroel',
                ],
            ],
        ],
        'galeria' => [
            'fotos' => [
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364773/bida-events/xv-isabella/gallery/1687302518_ujl0tm.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364778/bida-events/xv-isabella/gallery/259165536_xuowxd.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364782/bida-events/xv-isabella/gallery/229997590_cc0vwg.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364787/bida-events/xv-isabella/gallery/501124542_s75pve.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364792/bida-events/xv-isabella/gallery/298883069_omsxlg.jpg',
            ],
            'titulo' => 'Mis momentos',
        ],
        'musica' => [
            'titulo' => 'Mi canción',
            'artista' => 'Tate McRae - Greedy',
            'audio_url' => 'https://res.cloudinary.com/dwm7mniny/video/upload/v1789366270/bida-events/xv-isabella/musica/phpF871_dnyktb.mp3',
            'autoplay' => false,
        ],
        'video' => [
            'titulo' => 'Faltan pocos días',
            'video_url' => 'https://res.cloudinary.com/dwm7mniny/video/upload/c_limit,h_1280,q_auto,w_1280/v1789364801/bida-events/xv-isabella/video/838272301_epyvoh.mp4',
            'poster' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364810/bida-events/xv-isabella/video-poster/838272301-frame_x6fadt.jpg',
        ],
        'playlist' => [
            'titulo' => 'Canciones para la pista',
            'descripcion' => 'Sugiere la canción que quieres bailar conmigo.',
            'placeholder' => 'Nombre de la canción o link de YouTube',
        ],
        'hashtag' => [
            'hashtag' => '#IsabellaXV',
            'plataforma' => 'instagram',
            'texto_boton' => 'Comparte tus fotos',
        ],
        'encuestas' => [
            'preguntas' => [
                [
                    'id' => 'color-vestido',
                    'tipo' => 'single',
                    'pregunta' => '¿De qué color será mi vestido?',
                    'opciones' => ['Rosa palo', 'Champagne', 'Lila', 'Es sorpresa'],
                ],
                [
                    'id' => 'cancion-vals',
                    'tipo' => 'single',
                    'pregunta' => '¿Con qué canción bailaré el vals?',
                    'opciones' => ['A Thousand Years', 'Tiempo de vals', 'Perfect', 'Otra'],
                ],
                [
                    'id' => 'hora-loca',
                    'tipo' => 'yesno',
                    'pregunta' => '¿Te quedas hasta la hora loca?',
                    'opciones' => ['¡Obvio!', 'Me retiro temprano'],
                ],
                [
                    'id' => 'emocion',
                    'tipo' => 'rating',
                    'pregunta' => '¿Qué tanto te emociona la fiesta?',
                    'opciones' => ['1', '2', '3', '4', '5'],
                ],
            ],
            'titulo' => 'Juega conmigo',
        ],
        'regalos' => [
            'sobres' => [
                'titulo' => 'Lluvia de sobres',
                'direccion' => 'Habrá un cofre en la recepción del salón',
            ],
            'banco' => [
                'banco' => 'Banco Mercantil Santa Cruz',
                'titular' => 'Carolina Méndez de Rojas',
                'ci' => '4829173 LP',
                'cuenta' => '4010-2231-5587',
                'qr_url' => 'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364812/bida-events/xv-isabella/qr-banco/xv-isabella-qr_uggvqf.png',
            ],
            'titulo' => 'Regalos',
            'tienda_url' => '',
            'tienda_texto' => '',
            'opciones' => [],
        ],
        'post_evento' => [
            'titulo' => 'Fotos oficiales',
            'descripcion' => 'Las fotos del estudio ya están aquí. ¡Gracias por celebrar conmigo!',
            'fotos' => [
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364816/bida-events/xv-isabella/post-evento/258625283_olaf0p.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364821/bida-events/xv-isabella/post-evento/509470774_hijam6.jpg',
                'https://res.cloudinary.com/dwm7mniny/image/upload/v1789364825/bida-events/xv-isabella/post-evento/442777658_sboyj3.jpg',
            ],
            'enlace_externo' => '',
        ],
        'rsvp' => [
            'titulo_confirmacion' => 'Confirma tu asistencia',
            'mensaje_personalizado' => 'Por favor confirma antes del 10 de noviembre para reservar tu lugar.',
            'texto_confirmado' => '¡Gracias por confirmar! Presenta este pase en la entrada.',
            'texto_declinado' => 'Te voy a extrañar. Gracias por avisarme.',
        ],
        'cuenta_regresiva' => [],
        'agendar' => [],
        'fotomural' => [],
    ],
    'guests' => [
        [
            'name' => 'Familia Rojas Méndez',
            'phone' => '72476096',
            'passes_allocated' => 5,
            'passes_confirmed' => 5,
            'status' => 'confirmed',
            'table_number' => 'Mesa 1',
            'dietary_restrictions' => null,
            'qr_code_token' => 'D1GWYU7a2p8KDqtG8O5G9nQWdHad5YJU',
            'confirmed_at' => '2026-09-02 23:43:06',
        ],
        [
            'name' => 'Familia Mendoza',
            'phone' => '77850258',
            'passes_allocated' => 4,
            'passes_confirmed' => 4,
            'status' => 'confirmed',
            'table_number' => 'Mesa 2',
            'dietary_restrictions' => null,
            'qr_code_token' => '97Gf633x9VYGEB0OTIWcScJoX4oemuFy',
            'confirmed_at' => '2026-08-26 18:25:06',
        ],
        [
            'name' => 'Familia Arteaga',
            'phone' => '73144581',
            'passes_allocated' => 4,
            'passes_confirmed' => 3,
            'status' => 'confirmed',
            'table_number' => 'Mesa 2',
            'dietary_restrictions' => 'Una persona vegetariana',
            'qr_code_token' => 'fYuHuAvZj17Qbpl2qG9xq0N47RXEM3DY',
            'confirmed_at' => '2026-08-30 18:30:06',
        ],
        [
            'name' => 'Luciana Paz',
            'phone' => '74852677',
            'passes_allocated' => 2,
            'passes_confirmed' => 2,
            'status' => 'confirmed',
            'table_number' => 'Mesa 5',
            'dietary_restrictions' => null,
            'qr_code_token' => '6oa07yK4tw0QhZgRdBk9YBWIS479CCCt',
            'confirmed_at' => '2026-09-09 18:21:06',
        ],
        [
            'name' => 'Sebastián Rojas',
            'phone' => '71923452',
            'passes_allocated' => 1,
            'passes_confirmed' => 1,
            'status' => 'confirmed',
            'table_number' => 'Mesa 5',
            'dietary_restrictions' => null,
            'qr_code_token' => 'LN25MrwpmKchY5rp9pJokbjmfnosOERQ',
            'confirmed_at' => '2026-09-02 23:18:06',
        ],
        [
            'name' => 'Familia Salazar',
            'phone' => '71986566',
            'passes_allocated' => 3,
            'passes_confirmed' => 0,
            'status' => 'pending',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'o2r0ZBj5AOmThwLbwfSz9ZvdY6I0ZWDh',
            'confirmed_at' => null,
        ],
        [
            'name' => 'Familia Villarroel',
            'phone' => '78475277',
            'passes_allocated' => 4,
            'passes_confirmed' => 4,
            'status' => 'confirmed',
            'table_number' => 'Mesa 3',
            'dietary_restrictions' => 'Sin gluten',
            'qr_code_token' => 'qJsWOYMHPCPR0OtNzlq8cRjb3ttd2QPL',
            'confirmed_at' => '2026-09-08 20:10:06',
        ],
        [
            'name' => 'Tía Mónica Quiroga',
            'phone' => '73691942',
            'passes_allocated' => 2,
            'passes_confirmed' => 0,
            'status' => 'declined',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'nPPBozMhVjxnubSAz1bE21anNXe6WuPS',
            'confirmed_at' => '2026-09-04 23:18:06',
        ],
        [
            'name' => 'Profesora Elena Torrez',
            'phone' => '72567634',
            'passes_allocated' => 1,
            'passes_confirmed' => 0,
            'status' => 'pending',
            'table_number' => null,
            'dietary_restrictions' => null,
            'qr_code_token' => 'kmPazpX4iGvwtN18nORNOEAuDszGwdzR',
            'confirmed_at' => null,
        ],
        [
            'name' => 'Familia Suárez',
            'phone' => '78582922',
            'passes_allocated' => 4,
            'passes_confirmed' => 4,
            'status' => 'confirmed',
            'table_number' => 'Mesa 4',
            'dietary_restrictions' => null,
            'qr_code_token' => 'fEGU75dB3KureuutvCxYTXMBMEKfB3C1',
            'confirmed_at' => '2026-09-08 22:42:06',
        ],
    ],
    'contributions' => [
        [
            'guest' => 'D1GWYU7a2p8KDqtG8O5G9nQWdHad5YJU',
            'type' => 'song_request',
            'content_text' => 'Tusa — Karol G',
            'file_path' => null,
            'created_at' => '2026-09-02 16:48:06',
        ],
        [
            'guest' => '97Gf633x9VYGEB0OTIWcScJoX4oemuFy',
            'type' => 'song_request',
            'content_text' => 'Despechá — Rosalía',
            'file_path' => null,
            'created_at' => '2026-09-01 12:00:06',
        ],
        [
            'guest' => null,
            'type' => 'song_request',
            'content_text' => 'Vivir mi vida — Marc Anthony',
            'file_path' => null,
            'created_at' => '2026-09-06 19:40:06',
        ],
        [
            'guest' => '6oa07yK4tw0QhZgRdBk9YBWIS479CCCt',
            'type' => 'song_request',
            'content_text' => 'La Bachata — Manuel Turizo',
            'file_path' => null,
            'created_at' => '2026-09-01 23:31:06',
        ],
        [
            'guest' => 'LN25MrwpmKchY5rp9pJokbjmfnosOERQ',
            'type' => 'song_request',
            'content_text' => 'As It Was — Harry Styles',
            'file_path' => null,
            'created_at' => '2026-09-08 20:44:06',
        ],
        [
            'guest' => 'D1GWYU7a2p8KDqtG8O5G9nQWdHad5YJU',
            'type' => 'live_photo',
            'content_text' => null,
            'file_path' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_500,h_500,c_fill,q_auto,f_auto/v1789364831/bida-events/xv-isabella/fotomural/128158713_vqsoyy.jpg',
            'created_at' => '2026-09-12 17:47:13',
        ],
        [
            'guest' => '97Gf633x9VYGEB0OTIWcScJoX4oemuFy',
            'type' => 'live_photo',
            'content_text' => null,
            'file_path' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_500,h_500,c_fill,q_auto,f_auto/v1789364837/bida-events/xv-isabella/fotomural/296314487_cmcnki.jpg',
            'created_at' => '2026-09-12 02:47:18',
        ],
        [
            'guest' => 'fYuHuAvZj17Qbpl2qG9xq0N47RXEM3DY',
            'type' => 'live_photo',
            'content_text' => null,
            'file_path' => 'https://res.cloudinary.com/dwm7mniny/image/upload/w_500,h_500,c_fill,q_auto,f_auto/v1789364841/bida-events/xv-isabella/fotomural/308192017_jevuti.jpg',
            'created_at' => '2026-09-12 02:47:22',
        ],
    ],
    'poll_votes' => [
        [
            'poll' => 'color-vestido',
            'option' => 2,
            'guest' => 'D1GWYU7a2p8KDqtG8O5G9nQWdHad5YJU',
            'voter_key' => 'UKfDVfUYRW6jAOriqlte2nsIZ2TeHAlAk0B26dC7',
            'created_at' => '2026-09-13 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 2,
            'guest' => '97Gf633x9VYGEB0OTIWcScJoX4oemuFy',
            'voter_key' => 'EaygvbBZ426aDzo0pPhXHO9mDU0bQupjRRAXWFqT',
            'created_at' => '2026-09-04 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 2,
            'guest' => 'fYuHuAvZj17Qbpl2qG9xq0N47RXEM3DY',
            'voter_key' => 'ABzd7aBvZALekTEIw22M3f4sSmDUhuigl3FW2JLr',
            'created_at' => '2026-09-06 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 3,
            'guest' => '6oa07yK4tw0QhZgRdBk9YBWIS479CCCt',
            'voter_key' => 'YCdlPeyTPmocSUKR9W5zUtGI9BOeRFOup8hhvMU5',
            'created_at' => '2026-09-09 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 0,
            'guest' => 'LN25MrwpmKchY5rp9pJokbjmfnosOERQ',
            'voter_key' => 'n4sTc9m6oDozGgqsDuTnmUwxhIDoNq0KWeOOZSXF',
            'created_at' => '2026-09-12 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 2,
            'guest' => 'qJsWOYMHPCPR0OtNzlq8cRjb3ttd2QPL',
            'voter_key' => 'nxYuRJyjVvYf4Odu9fnRZrm8EZiMS5SwKLSzw9Ya',
            'created_at' => '2026-09-09 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 2,
            'guest' => 'fEGU75dB3KureuutvCxYTXMBMEKfB3C1',
            'voter_key' => '9hYFDdqlIRKNoqUo3JXLg5UdNF9ytjJnDCgDEyAK',
            'created_at' => '2026-08-30 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'tMWUtwwjudpMRlRmOdaXuKn9iFIFJMatjO83v9BS',
            'created_at' => '2026-09-11 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'qHP6hvqs6HokJneDi7HNy7bSY8BJzdBkSTjPo9Vx',
            'created_at' => '2026-09-06 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'gMSW5i6OVyn9MFYHWWQyW3x9JezS2x25tsKCaSx8',
            'created_at' => '2026-08-30 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'VESHBl6ialOvZsogZPfbNJRjk0TSoFoH0RR5DkQ6',
            'created_at' => '2026-09-11 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 2,
            'guest' => null,
            'voter_key' => '6sjrQ0hx9niH5susccN96cue3NLmqJqfUGyx3taq',
            'created_at' => '2026-09-01 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'c6QMbuBfOQQzPaaeobe7azkHpLTj5pYkPwXlzqCm',
            'created_at' => '2026-09-02 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 2,
            'guest' => null,
            'voter_key' => 's2qV6LQKO7XoCGK1Xq8a019P4f90mTHW4AuMOooV',
            'created_at' => '2026-08-30 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'OeNWxZKj6xJFRQHiHVDm9TzgjpGZa6HlgvgIJyoz',
            'created_at' => '2026-09-03 01:47:22',
        ],
        [
            'poll' => 'color-vestido',
            'option' => 1,
            'guest' => null,
            'voter_key' => '0D1yco7LyqSEnJtyrzk1eLaGfg5Glwtg4iGs5APt',
            'created_at' => '2026-09-01 01:47:22',
        ],
        [
            'poll' => 'cancion-vals',
            'option' => 2,
            'guest' => 'D1GWYU7a2p8KDqtG8O5G9nQWdHad5YJU',
            'voter_key' => 'vio2eqSumAZLJETVLgfcNA0EBVHBDjV4pbUYdfq6',
            'created_at' => '2026-09-05 01:47:22',
        ],
        [
            'poll' => 'cancion-vals',
            'option' => 1,
            'guest' => '97Gf633x9VYGEB0OTIWcScJoX4oemuFy',
            'voter_key' => 'jlwifLTrgg0tITb0XOon086Oz2X7k4jUY2ytvS83',
            'created_at' => '2026-09-08 01:47:22',
        ],
        [
            'poll' => 'cancion-vals',
            'option' => 3,
            'guest' => 'fYuHuAvZj17Qbpl2qG9xq0N47RXEM3DY',
            'voter_key' => 'EH2LCbV5Pu7ljdHICklMaRa4K9rB0ccwFUydwpvo',
            'created_at' => '2026-08-30 01:47:22',
        ],
        [
            'poll' => 'cancion-vals',
            'option' => 3,
            'guest' => '6oa07yK4tw0QhZgRdBk9YBWIS479CCCt',
            'voter_key' => 'l5hBs2umN55feIUemsJY3S0yjvoUQfm4mFqnODvD',
            'created_at' => '2026-09-14 01:47:22',
        ],
        [
            'poll' => 'cancion-vals',
            'option' => 2,
            'guest' => 'LN25MrwpmKchY5rp9pJokbjmfnosOERQ',
            'voter_key' => 'rl1N6onwo66Q0zcYTzjLqM4j6uDSHKBVMmsuHeje',
            'created_at' => '2026-09-13 01:47:22',
        ],
        [
            'poll' => 'cancion-vals',
            'option' => 2,
            'guest' => 'qJsWOYMHPCPR0OtNzlq8cRjb3ttd2QPL',
            'voter_key' => 'TAQWnpyCbKKhETPI3sIU6ewn6psATCR3skOLpq0e',
            'created_at' => '2026-09-04 01:47:22',
        ],
        [
            'poll' => 'cancion-vals',
            'option' => 2,
            'guest' => 'fEGU75dB3KureuutvCxYTXMBMEKfB3C1',
            'voter_key' => '0s6ATrbrz6rpT2fPHM8i8xLAXDzmnhQniKkXTx1F',
            'created_at' => '2026-09-02 01:47:22',
        ],
        [
            'poll' => 'cancion-vals',
            'option' => 1,
            'guest' => null,
            'voter_key' => '2FUrCgIs9NFqlj3v0z1yqVLZICoqWoWTdFhyMLKR',
            'created_at' => '2026-09-09 01:47:22',
        ],
        [
            'poll' => 'cancion-vals',
            'option' => 3,
            'guest' => null,
            'voter_key' => 'E6HWrcRDnkihv3565nMKj1J8YiTv9GXlOc2bucB3',
            'created_at' => '2026-09-06 01:47:22',
        ],
        [
            'poll' => 'cancion-vals',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'htJyc4wnzFFAQb4KTLP9vS2CRDvM278zrNn5FaaH',
            'created_at' => '2026-09-01 01:47:22',
        ],
        [
            'poll' => 'cancion-vals',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'wQadRkcXwVdNXabUcUzZeaKtzEEsu170n2JeglZG',
            'created_at' => '2026-09-08 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => 'D1GWYU7a2p8KDqtG8O5G9nQWdHad5YJU',
            'voter_key' => 'rqkZUrLum0ZFMivA753sB4KxZu1QTElGV5A7OhE0',
            'created_at' => '2026-09-06 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => '97Gf633x9VYGEB0OTIWcScJoX4oemuFy',
            'voter_key' => 'A7ax63i7Jb1CoI9LSiPDbcZN9SDKQhOTfHNY9txt',
            'created_at' => '2026-09-06 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => 'fYuHuAvZj17Qbpl2qG9xq0N47RXEM3DY',
            'voter_key' => 'QF4z7q7X4m602RFym9Vna3EaV9PR8DKncX0Er8lt',
            'created_at' => '2026-09-13 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => '6oa07yK4tw0QhZgRdBk9YBWIS479CCCt',
            'voter_key' => 'oUYob7xJCTl8fRz2iaKwRge1zofaGSOJoR8xv2RN',
            'created_at' => '2026-09-10 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => 'LN25MrwpmKchY5rp9pJokbjmfnosOERQ',
            'voter_key' => 'G8HAF3JKUzi4rKhGsvlYIs4bCQGHfOga5771dlSm',
            'created_at' => '2026-09-11 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => 'qJsWOYMHPCPR0OtNzlq8cRjb3ttd2QPL',
            'voter_key' => 'rSxQs9vji58IIVg22jkHoksuAlQvnB3HHKA7rIsn',
            'created_at' => '2026-09-01 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => 'fEGU75dB3KureuutvCxYTXMBMEKfB3C1',
            'voter_key' => 'FwAR35M68Kou8DtSyPIo1WbM1J9PiVXHgmbr1McT',
            'created_at' => '2026-09-05 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => null,
            'voter_key' => '5Ezyd7z4OjWc2QXjJ9XeYxvNmtIoxQd8Mp8VkjA8',
            'created_at' => '2026-09-03 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'LBN77w2VGY25u5KedhKGfRMlPzwMMkGDpHBf8ag4',
            'created_at' => '2026-09-12 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'rkGxop79pJT8upBO0A8pPioRPKUSTJ7V8wmIkQsS',
            'created_at' => '2026-09-12 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'IJXzdqfwvuy9KKZ96MjV4dXgWaoBcwoeZfjGVSmX',
            'created_at' => '2026-09-04 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'KcyJNjTaIP1Aw15F4uPDoJKp8vj7XuN1BvYkQEqf',
            'created_at' => '2026-09-03 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'j8VgXuLVCySpSBBeJ3PLFfjmx8VMsxbmUGAwJ4VH',
            'created_at' => '2026-09-04 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'OGnziQMFIfrAVmJYPpp4jonJvUjbB8qjDJ7GLMH3',
            'created_at' => '2026-09-10 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'pGqpFD0HMQJ84FTYyvvahXoqr7xRyG2RXiw3OTD2',
            'created_at' => '2026-09-09 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'vCCBpcnsHckTqC4r1vG3CalSvOUSaHTfvKPejtWl',
            'created_at' => '2026-09-13 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'LniIJlIeojMiMls2qlgmIl7Et2a4djUo1ucoGumy',
            'created_at' => '2026-09-12 01:47:22',
        ],
        [
            'poll' => 'hora-loca',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'UVcQnydbuVKXs624PRyCmF7FCf7kYXqzY8jfN0Am',
            'created_at' => '2026-09-09 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 0,
            'guest' => 'D1GWYU7a2p8KDqtG8O5G9nQWdHad5YJU',
            'voter_key' => 'm2IBxTw7OXDAm1e5nKNB1gg0bKX8zjhMqqAIa9ED',
            'created_at' => '2026-09-01 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 3,
            'guest' => '97Gf633x9VYGEB0OTIWcScJoX4oemuFy',
            'voter_key' => 'a9lJpllKtPt59g3WAryqQ4PYXmFNPO9gf64AHDUy',
            'created_at' => '2026-09-03 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 0,
            'guest' => 'fYuHuAvZj17Qbpl2qG9xq0N47RXEM3DY',
            'voter_key' => 'wGQDsROQ4RZKDqPcyzyTU2IQYAdiCV4MZrNWnHb0',
            'created_at' => '2026-09-07 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 0,
            'guest' => '6oa07yK4tw0QhZgRdBk9YBWIS479CCCt',
            'voter_key' => 'qT7KHJ87loGbmC7Crz1ETJsPZr3kYzBwOPWU9yIZ',
            'created_at' => '2026-09-10 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 2,
            'guest' => 'LN25MrwpmKchY5rp9pJokbjmfnosOERQ',
            'voter_key' => 'PTjjJ9DZVqm30QbZIQAYtQd581pbFjVyKQAnLVlK',
            'created_at' => '2026-09-10 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 2,
            'guest' => 'qJsWOYMHPCPR0OtNzlq8cRjb3ttd2QPL',
            'voter_key' => 'yKzWOFyblWDQS9lKfCYCoNgNYTmDJLNHYjtRF4rX',
            'created_at' => '2026-09-04 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 0,
            'guest' => 'fEGU75dB3KureuutvCxYTXMBMEKfB3C1',
            'voter_key' => 'MF53cU0FwUdCvNvgeEUZGcI7LGWYopfuASp5A1er',
            'created_at' => '2026-09-07 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 2,
            'guest' => null,
            'voter_key' => '9XpNKxnCJgmEtvnGHoiYWJK60LgKmpMATR58v2Fp',
            'created_at' => '2026-09-05 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'IROJ1mi17vPBPRuBNwCLaaIHgICaD6g4JsuwXMFE',
            'created_at' => '2026-08-30 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'SxfRTkFsEH6OBcK7PXYPsMocQUxDkXO9U6bAf5AV',
            'created_at' => '2026-09-04 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'dHYgk3ijnHl3WzbiKcMaICWLf3SjuBGgrkqzDcLA',
            'created_at' => '2026-09-11 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 4,
            'guest' => null,
            'voter_key' => 'tWkdC2ochwNoURqAuySkrFsNzggbRwCWg4rrRWoJ',
            'created_at' => '2026-09-14 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 2,
            'guest' => null,
            'voter_key' => 'Pek4AQbCTUXLVML4bvzRtVZGpCRYSdZb6FlY6kPm',
            'created_at' => '2026-09-03 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 1,
            'guest' => null,
            'voter_key' => 'RDo1li6C02j7UCvBIFpTuEzt33npWRsRF6FD4SQt',
            'created_at' => '2026-09-02 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'THnMVItD746tMPU8hAoCM1SaGxCbpJl5a3pkbZVZ',
            'created_at' => '2026-09-14 01:47:22',
        ],
        [
            'poll' => 'emocion',
            'option' => 0,
            'guest' => null,
            'voter_key' => 'MsQttzRnBadzZbr09UhAcj7QexwMRYaYVQ2CIwSK',
            'created_at' => '2026-09-14 01:47:22',
        ],
    ],
];
